rule ExtSentry_malware_BrowserExtensions
{
    meta:
        description = "Detects browser extension IDs categorized as malware by ExtSentry"
        author = "ExtSentry / mthcht"
        date = "2026-03-27"
        reference = "https://github.com/mthcht/awesome-lists"
        category = "malware"
        tlp = "WHITE"

    strings:
        $ext_0 = "fpeabamapgecnidibdmjoepaiehokgda" ascii wide
        $ext_1 = "ajfanjhcdgaohcbphpaceglgpgaaohod" ascii wide
        $ext_2 = "eeoonfhmbjlmienmmbgapfloddpmoalh" ascii wide
        $ext_3 = "hokdpdlchkgcenfpiibjjfkfmleoknkp" ascii wide
        $ext_4 = "jaioobipjdejpeckgojiojjahmkiaihp" ascii wide
        $ext_5 = "akdajpomgjgldidenledjjiemgkjcchc" ascii wide
        $ext_6 = "mkkfklcadlnkhgapjeejemflhamcdjld" ascii wide
        $ext_7 = "kfokdmfpdnokpmpbjhjbcabgligoelgp" ascii wide
        $ext_8 = "pdadlkbckhinonakkfkdaadceojbekep" ascii wide
        $ext_9 = "akmdionenlnfcipmdhbhcnkighafmdha" ascii wide
        $ext_10 = "pabkjoplheapcclldpknfpcepheldbga" ascii wide
        $ext_11 = "aedgpiecagcpmehhelbibfbgpfiafdkm" ascii wide
        $ext_12 = "dpdgjbnanmmlikideilnpfjjdbmneanf" ascii wide
        $ext_13 = "kabbfhmcaaodobkfbnnehopcghicgffo" ascii wide
        $ext_14 = "cphibdhgbdoekmkkcbbaoogedpfibeme" ascii wide
        $ext_15 = "ceofheakaalaecnecdkdanhejojkpeai" ascii wide
        $ext_16 = "dakebdbeofhmlnmjlmhjdmmjmfohiicn" ascii wide
        $ext_17 = "adjoknoacleghaejlggocbakidkoifle" ascii wide
        $ext_18 = "pgpidfocdapogajplhjofamgeboonmmj" ascii wide
        $ext_19 = "ifklcpoenaammhnoddgedlapnodfcjpn" ascii wide
        $ext_20 = "ebhomdageggjbmomenipfbhcjamfkmbl" ascii wide
        $ext_21 = "ajfokipknlmjhcioemgnofkpmdnbaldi" ascii wide
        $ext_22 = "mhjdjckeljinofckdibjiojbdpapoecj" ascii wide
        $ext_23 = "aikflfpejipbpjdlfabpgclhblkpaafo" ascii wide
        $ext_24 = "dbfmnekepjoapopniengjbcpnbljalfg" ascii wide
        $ext_25 = "nnnkddnnlpamobajfibfdgfnbcnkgngh" ascii wide
        $ext_26 = "ppfdcmempdfjnanjegmjhanplgjicefg" ascii wide
        $ext_27 = "fmiefmaepcnjahoajkfckenfngfehhma" ascii wide
        $ext_28 = "edojphplonjclmfckdiolpahpgcanjnh" ascii wide
        $ext_29 = "bjehnpiidogpaocjjfhnopdjcahigggm" ascii wide
        $ext_30 = "kdgjiakonpbfmndaacfhamdoangincgp" ascii wide
        $ext_31 = "dihekmadkkcgnffajefocfamnpimlhah" ascii wide
        $ext_32 = "eijnkinhnplaekpllmgbbfieecdhcmcp" ascii wide
        $ext_33 = "mdlkdelnchilkeedllnnjfigkhhadlff" ascii wide
        $ext_34 = "agepkkdokhlaoiaenedmjbfnblfdiboc" ascii wide
        $ext_35 = "epepbcdeelckgplpmmmnmjplbeipgllo" ascii wide
        $ext_36 = "makeekhnfplggoaiklkphfopajegajci" ascii wide
        $ext_37 = "cahdpfhnokmnnjhoaoliabdbcbbokmgc" ascii wide
        $ext_38 = "mmpfmolbdhdfoblfggigchncdgmdnjha" ascii wide
        $ext_39 = "knejepegjmjmjlhficbikmblnbemdpke" ascii wide
        $ext_40 = "cjlabngphhjjdapemkdnpgkpebkpjbbe" ascii wide
        $ext_41 = "jeaebbdndojkbnnfcaihgokhnakocbnf" ascii wide
        $ext_42 = "bajoeadpdidoahbhphmhejmbdmgnbdci" ascii wide
        $ext_43 = "goiffchdhlcehhgdpdbocefkohlhmlom" ascii wide
        $ext_44 = "djkddblnfgendjoklmfmocaboelkmdkm" ascii wide
        $ext_45 = "codgofkgobbmgglciccjabipdlgefnch" ascii wide
        $ext_46 = "cicnbbdlbjaoioilpbdioeeaockgbhfi" ascii wide
        $ext_47 = "mchacgmgddefeohkjobefhihbadocneh" ascii wide
        $ext_48 = "oelcnhfgpdjeocflhhfecinnpjojeokp" ascii wide
        $ext_49 = "fllcifcfhgmmfpogmpedgbjccnjalpjo" ascii wide
        $ext_50 = "fmgaogkbodhdhhbgkphhbokciiecllno" ascii wide
        $ext_51 = "dkbpkjhegfanacodkmfjeackckmehkfp" ascii wide
        $ext_52 = "jooiimddfkjoomennmpjabdbbpdocjng" ascii wide
        $ext_53 = "dekjibpkbhgbnmnfibnibnjoccaphfog" ascii wide
        $ext_54 = "mnamhmcgcfflfjafflanbhbfffpmkmmm" ascii wide
        $ext_55 = "ambcheakfbokmebglefpbbphbccekhhl" ascii wide
        $ext_56 = "nmaegedpdmepbkahckadmaolllgmogma" ascii wide
        $ext_57 = "doeomodlafdbbnajjllemacdfphbbohl" ascii wide
        $ext_58 = "meobjhkdifjealkiaanikkpajiaalcad" ascii wide
        $ext_59 = "kfdopiiledmclnopmihkclnfgdiggjna" ascii wide
        $ext_60 = "cfgiodgnkinmacjkgjgdejeciohojglp" ascii wide
        $ext_61 = "okepehobneenpbhiendcjcanjodhmcbj" ascii wide
        $ext_62 = "cdgonefipacceedbkflolomdegncceid" ascii wide
        $ext_63 = "bgkdocoihppjkdfaghndpjlfoehjcmka" ascii wide
        $ext_64 = "ldmnodpmebcfcdkejkdakphbcjnmejlf" ascii wide
        $ext_65 = "pdfladlchakneeclhmpoboohikpbchkj" ascii wide
        $ext_66 = "gipnpcencdgljnaecpekokmpgnhgpela" ascii wide
        $ext_67 = "idholfkkmfccbondfiabhlmdfeamnnaj" ascii wide
        $ext_68 = "bpgaffohfacaamplbbojgbiicfgedmoi" ascii wide
        $ext_69 = "jdehnhjckcbfdkgnlbfjokofagpbbdgl" ascii wide
        $ext_70 = "dijcdmefkmlhnbkcejcmepheakikgpdg" ascii wide
        $ext_71 = "gndlcpbcmhbcaadppjjekgbhfhceeikm" ascii wide
        $ext_72 = "lepdjbhbkpfenckechpdfohdmkhogojf" ascii wide
        $ext_73 = "hbjeophpjnopmeheabcilmgdhnnjbmbo" ascii wide
        $ext_74 = "dlfjoijnhjeagkenhbililbdiooginng" ascii wide
        $ext_75 = "kolgdodmgnnhnijmnnidfabnghgakobl" ascii wide
        $ext_76 = "edohfgmjmdnibeihfcajfclmhapjkooa" ascii wide
        $ext_77 = "pdjpkfbpeniinkdlmibcdebccnkimnna" ascii wide
        $ext_78 = "hmpjibmngagmkafmijncjokocepchnea" ascii wide
        $ext_79 = "kljbaedmklfnlgfmmbodnckafhllkjnd" ascii wide
        $ext_80 = "lmppkgmbapjgihlpadknmfalefnfnfnd" ascii wide
        $ext_81 = "ldghoefcghcinacfneopmnechojlhldf" ascii wide
        $ext_82 = "mgjfjcimpkdjgeldkcaoboiojmlcleka" ascii wide
        $ext_83 = "aghafppaelpjbjajpgcogcojcbmappoi" ascii wide
        $ext_84 = "kgdjeaonamhfooejllllfpeappcgfpod" ascii wide
        $ext_85 = "knjgknhkgmedmajpkhooaagjgfgbcndo" ascii wide
        $ext_86 = "apoklfecapckgpbbcpaiebemaghmkncf" ascii wide
        $ext_87 = "podfjomopoejmlkfnhanlmlagcnlappd" ascii wide
        $ext_88 = "idngjfdlfbfgecemidnhbdcogggnjkpg" ascii wide
        $ext_89 = "kghabofklgjfnipgkjadlogcjbebkeid" ascii wide
        $ext_90 = "fmmfeaoidanfcipomjfolmchjdnhmaio" ascii wide
        $ext_91 = "cfmfokegjjljmdcdpnmlfajlddngkoah" ascii wide
        $ext_92 = "eoimljninkkepafoijpgbedkkieobfek" ascii wide
        $ext_93 = "ojmaccnnagaiokckbcpdldhnifkibcah" ascii wide
        $ext_94 = "bhoebgegnjoehioianjnjakeeggajanb" ascii wide
        $ext_95 = "edojphplonjclmfckdiolpahpgcanjnh" ascii wide
        $ext_96 = "leaglmohfmgdengbciphnodmcgfgdgnf" ascii wide
        $ext_97 = "ljdhejdbbogemelgkihbabifpfdfomcc" ascii wide
        $ext_98 = "hfokkkgobhlkcagflcbgcokdbnknfngo" ascii wide
        $ext_99 = "hilgkhepkfjdkkdigphhcgmghefdledg" ascii wide
        $ext_100 = "jipclfaahkhinbelbojjblmbcpkaipko" ascii wide
        $ext_101 = "cmckpheolajgbmhlfhgelajhhfgjbhpk" ascii wide
        $ext_102 = "jjdhjfgoadphekgihokkigfghndfmffb" ascii wide
        $ext_103 = "nelegdbdfopcgkignnifhdoiapldlhpf" ascii wide
        $ext_104 = "dnojfjfegklgconkoekfkaajejmdgdkj" ascii wide
        $ext_105 = "nnceocbiolncfljcmajijmeakcdlffnh" ascii wide
        $ext_106 = "dacliiapfipnlipdmifioaijepgmhdga" ascii wide
        $ext_107 = "cpbbiepjnljbnngpepgeaojjeneacpld" ascii wide
        $ext_108 = "ocopipabchoopeppmgiigphgbicocoea" ascii wide
        $ext_109 = "gfechfioaanebemclajhfgkfaopcaibo" ascii wide
        $ext_110 = "hoclolhilhbecpefaignjficiaaclpop" ascii wide
        $ext_111 = "ibmdocjlknaopfecmnojomdlbeadpdnb" ascii wide
        $ext_112 = "ckdbfeccfocmhdclmmofmheljglmhhne" ascii wide
        $ext_113 = "gddkghdkhhlihaabphhnjbhdoiifhcpa" ascii wide
        $ext_114 = "nlhpidbjmmffhoogcennoiopekbiglbp" ascii wide
        $ext_115 = "gcfianbpjcfkafpiadmheejkokcmdkjl" ascii wide
        $ext_116 = "fppbiomdkfbhgjjdmojlogeceejinadg" ascii wide
        $ext_117 = "djhjckkfgancelbmgcamjimgphaphjdl" ascii wide
        $ext_118 = "llojfncgbabajmdglnkbhmiebiinohek" ascii wide
        $ext_119 = "gghdfkafnhfpaooiolhncejnlgglhkhe" ascii wide
        $ext_120 = "cgmmcoandmabammnhfnjcakdeejbfimn" ascii wide
        $ext_121 = "phiphcloddhmndjbdedgfbglhpkjcffh" ascii wide
        $ext_122 = "pgfibniplgcnccdnkhblpmmlfodijppg" ascii wide
        $ext_123 = "nkgbfengofophpmonladgaldioelckbe" ascii wide
        $ext_124 = "gcdfailafdfjbailcdcbjmeginhncjkb" ascii wide
        $ext_125 = "ebmmjmakencgmgoijdfnbailknaaiffh" ascii wide
        $ext_126 = "baonbjckakcpgliaafcodddkoednpjgf" ascii wide
        $ext_127 = "fdlagfnfaheppaigholhoojabfaapnhb" ascii wide
        $ext_128 = "gnaekhndaddbimfllbgmecjijbbfpabc" ascii wide
        $ext_129 = "hgnjolbjpjmhepcbjgeeallnamkjnfgi" ascii wide
        $ext_130 = "lodlcpnbppgipaimgbjgniokjcnpiiad" ascii wide
        $ext_131 = "cmpmhhjahlioglkleiofbjodhhiejhei" ascii wide
        $ext_132 = "bilfflcophfehljhpnklmcelkoiffapb" ascii wide
        $ext_133 = "cicjlpmjmimeoempffghfglndokjihhn" ascii wide
        $ext_134 = "ckneindgfbjnbbiggcmnjeofelhflhaj" ascii wide
        $ext_135 = "dbclhjpifdfkofnmjfpheiondafpkoed" ascii wide
        $ext_136 = "ecikmpoikkcelnakpgaeplcjoickgacj" ascii wide
        $ext_137 = "kepibgehhljlecgaeihhnmibnmikbnga" ascii wide
        $ext_138 = "ckicoadchmmndbakbokhapncehanaeni" ascii wide
        $ext_139 = "fnjinbdmidgjkpmlihcginjipjaoapol" ascii wide
        $ext_140 = "gohgeedemmaohocbaccllpkabadoogpl" ascii wide
        $ext_141 = "flnecpdpbhdblkpnegekobahlijbmfok" ascii wide
        $ext_142 = "acaeafediijmccnjlokgcdiojiljfpbe" ascii wide
        $ext_143 = "kblengdlefjpjkekanpoidgoghdngdgl" ascii wide
        $ext_144 = "idhknpoceajhnjokpnbicildeoligdgh" ascii wide
        $ext_145 = "fpmkabpaklbhbhegegapfkenkmpipick" ascii wide
        $ext_146 = "lmiigijnefpkjcenfbinhdpafehaddag" ascii wide
        $ext_147 = "obdobankihdfckkbfnoglefmdgmblcld" ascii wide
        $ext_148 = "kefnabicobeigajdngijnnjmljehknjl" ascii wide
        $ext_149 = "ifjimhnbnbniiiaihphlclkpfikcdkab" ascii wide
        $ext_150 = "pfgbcfaiglkcoclichlojeaklcfboieh" ascii wide
        $ext_151 = "hljdedgemmmkdalbnmnpoimdedckdkhm" ascii wide
        $ext_152 = "afjenpabhpfodjpncbiiahbknnghabdc" ascii wide
        $ext_153 = "gbcgjnbccjojicobfimcnfjddhpphaod" ascii wide
        $ext_154 = "ipjgfhcjeckaibnohigmbcaonfcjepmb" ascii wide
        $ext_155 = "mmjmcfaejolfbenlplfoihnobnggljij" ascii wide
        $ext_156 = "lechagcebaneoafonkbfkljmbmaaoaec" ascii wide
        $ext_157 = "nhnfaiiobkpbenbbiblmgncgokeknnno" ascii wide
        $ext_158 = "hpcejjllhbalkcmdikecfngkepppoknd" ascii wide
        $ext_159 = "hfdpdgblphooommgcjdnnmhpglleaafj" ascii wide
        $ext_160 = "ioaeacncbhpmlkediaagefiegegknglc" ascii wide
        $ext_161 = "jhohjhmbiakpgedidneeloaoloadlbdj" ascii wide
        $ext_162 = "kgmeffmlnkfnjpgmdndccklfigfhajen" ascii wide
        $ext_163 = "dpdibkjjgbaadnnjhkmmnenkmbnhpobj" ascii wide
        $ext_164 = "gaiceihehajjahakcglkhmdbbdclbnlf" ascii wide
        $ext_165 = "mlgbkfnjdmaoldgagamcnommbbnhfnhf" ascii wide
        $ext_166 = "eckokfcjbjbgjifpcbdmengnabecdakp" ascii wide
        $ext_167 = "mgbhdehiapbjamfgekfpebmhmnmcmemg" ascii wide
        $ext_168 = "cbajickflblmpjodnjoldpiicfmecmif" ascii wide
        $ext_169 = "pdbfcnhlobhoahcamoefbfodpmklgmjm" ascii wide
        $ext_170 = "eokjikchkppnkdipbiggnmlkahcdkikp" ascii wide
        $ext_171 = "ihbiedpeaicgipncdnnkikeehnjiddck" ascii wide
        $ext_172 = "jjdajogomggcjifnjgkpghcijgkbcjdi" ascii wide
        $ext_173 = "mmcnmppeeghenglmidpmjkaiamcacmgm" ascii wide
        $ext_174 = "ojdkklpgpacpicaobnhankbalkkgaafp" ascii wide
        $ext_175 = "lodeighbngipjjedfelnboplhgediclp" ascii wide
        $ext_176 = "hkjagicdaogfgdifaklcgajmgefjllmd" ascii wide
        $ext_177 = "gflkbgebojohihfnnplhbdakoipdbpdm" ascii wide
        $ext_178 = "kpilmncnoafddjpnbhepaiilgkdcieaf" ascii wide
        $ext_179 = "caibdnkmpnjhjdfnomfhijhmebigcelo" ascii wide
        $ext_180 = "caibdnkmpnjhjdfnomfhijhmebigcelo" ascii wide
        $ext_181 = "ceibjdigmfbbgcpkkdpmjokkokklodmc" ascii wide
        $ext_182 = "mflibpdjoodmoppignjhciadahapkoch" ascii wide
        $ext_183 = "lgakkahjfibfgmacigibnhcgepajgfdb" ascii wide
        $ext_184 = "bndkfmmbidllaiccmpnbdonijmicaafn" ascii wide
        $ext_185 = "pcdgkgbadeggbnodegejccjffnoakcoh" ascii wide
        $ext_186 = "oldhjammhkghhahhhdcifmmlefibciph" ascii wide
        $ext_187 = "ijapakghdgckgblfgjobhcfglebbkebf" ascii wide
        $ext_188 = "makdmacamkifdldldlelollkkjnoiedg" ascii wide
        $ext_189 = "mbjjeombjeklkbndcjgmfcdhfbjngcam" ascii wide
        $ext_190 = "bmodapcihjhklpogdpblefpepjolaoij" ascii wide
        $ext_191 = "fbfldogmkadejddihifklefknmikncaj" ascii wide
        $ext_192 = "ocpcmfmiidofonkbodpdhgddhlcmcofd" ascii wide
        $ext_193 = "fgpecemjbefkjlcgnhjohdonijdkfooj" ascii wide
        $ext_194 = "kekfppnajjchccpkfaogiomfcncbgagc" ascii wide
        $ext_195 = "nhiafglcjghpmcipelflfhkckdpcokid" ascii wide
        $ext_196 = "hfofhoffdcfcjgmilkpnhkamcgemaban" ascii wide
        $ext_197 = "foiopecknacmiihiocgdjgbjokkpkohc" ascii wide
        $ext_198 = "bibjcjfmgapbfoljiojpipaooddpkpai" ascii wide
        $ext_199 = "ngahaphlngmdfhbhkplbglnfhehnpgdb" ascii wide
        $ext_200 = "ibibeegnncapfdcgpdnnbjbbojglhlmk" ascii wide
        $ext_201 = "anlhakiodmebohjmkbciohpglnjifjaa" ascii wide
        $ext_202 = "glckmpfajbjppappjlnhhlofhdhlcgaj" ascii wide
        $ext_203 = "giecgobdmgdamgffeoankaipjkdjbfep" ascii wide
        $ext_204 = "bjoddpbfndnpeohkmpbjfhcppkhgobcg" ascii wide
        $ext_205 = "beifiidafjobphnbhbbgmgnndjolfcho" ascii wide
        $ext_206 = "eagiakjmjnblliacokhcalebgnhellfi" ascii wide
        $ext_207 = "ibiejjpajlfljcgjndbonclhcbdcamai" ascii wide
        $ext_208 = "ogjneoecnllmjcegcfpaamfpbiaaiekh" ascii wide
        $ext_209 = "jbnopeoocgbmnochaadfnhiiimfpbpmf" ascii wide
        $ext_210 = "cdgonefipacceedbkflolomdegncceid" ascii wide
        $ext_211 = "gipnpcencdgljnaecpekokmpgnhgpela" ascii wide
        $ext_212 = "bpgaffohfacaamplbbojgbiicfgedmoi" ascii wide
        $ext_213 = "ineempkjpmbdejmdgienaphomigjjiej" ascii wide
        $ext_214 = "nnnklgkfdfbdijeeglhjfleaoagiagig" ascii wide
        $ext_215 = "mljmfnkjmcdmongjnnnbbnajjdbojoci" ascii wide
        $ext_216 = "llkncpcdceadgibhbedecmkencokjajg" ascii wide
        $ext_217 = "nmfbniajnpceakchicdhfofoejhgjefb" ascii wide
        $ext_218 = "ijcpbhmpbaafndchbjdjchogaogelnjl" ascii wide
        $ext_219 = "olaahjgjlhoehkpemnfognpgmkbedodk" ascii wide
        $ext_220 = "gnhgdhlkojnlgljamagoigaabdmfhfeg" ascii wide
        $ext_221 = "cihbmmokhmieaidfgamioabhhkggnehm" ascii wide
        $ext_222 = "lehjnmndiohfaphecnjhopgookigekdk" ascii wide
        $ext_223 = "hlcjkaoneihodfmonjnlnnfpdcopgfjk" ascii wide
        $ext_224 = "hmhifpbclhgklaaepgbabgcpfgidkoei" ascii wide
        $ext_225 = "lnlononncfdnhdfmgpkdfoibmfdehfoj" ascii wide
        $ext_226 = "nagbiboibhbjbclhcigklajjdefaiidc" ascii wide
        $ext_227 = "ofkopmlicnffaiiabnmnaajaimmenkjn" ascii wide
        $ext_228 = "ocffbdeldlbilgegmifiakciiicnoaeo" ascii wide
        $ext_229 = "eaokmbopbenbmgegkmoiogmpejlaikea" ascii wide
        $ext_230 = "lhiehjmkpbhhkfapacaiheolgejcifgd" ascii wide
        $ext_231 = "ondhgmkgppbdnogfiglikgpdkmkaiggk" ascii wide
        $ext_232 = "imdgpklnabbkghcbhmkbjbhcomnfdige" ascii wide
        $ext_233 = "bpelnogcookhocnaokfpoeinibimbeff" ascii wide
        $ext_234 = "enkihkfondbngohnmlefmobdgkpmejha" ascii wide
        $ext_235 = "hajlmbnnniemimmaehcefkamdadpjlfa" ascii wide
        $ext_236 = "aadnmeanpbokjjahcnikajejglihibpd" ascii wide
        $ext_237 = "ipnidmjhnoipibbinllilgeohohehabl" ascii wide
        $ext_238 = "fnnigcfbmghcefaboigkhfimeolhhbcp" ascii wide
        $ext_239 = "nlcebdoehkdiojeahkofcfnolkleembf" ascii wide
        $ext_240 = "fhababnomjcnhmobbemagohkldaeicad" ascii wide
        $ext_241 = "nokknhlkpdfppefncfkdebhgfpfilieo" ascii wide
        $ext_242 = "ljmcneongnlaecabgneiippeacdoimaa" ascii wide
        $ext_243 = "onifebiiejdjncjpjnojlebibonmnhog" ascii wide
        $ext_244 = "dbagndmcddecodlmnlcmhheicgkaglpk" ascii wide
        $ext_245 = "fmgfcpjmmapcjlknncjgmbolgaecngfo" ascii wide
        $ext_246 = "kgmlodoegkmpfkbepkfhgeldidodgohd" ascii wide
        $ext_247 = "hegpgapbnfiibpbkanjemgmdpmmlecbc" ascii wide
        $ext_248 = "gkanlgbbnncfafkhlchnadcopcgjkfli" ascii wide
        $ext_249 = "oghgaghnofhhoolfneepjneedejcpiic" ascii wide
        $ext_250 = "fcidgbgogbfdcgijkcfdjcagmhcelpbc" ascii wide
        $ext_251 = "nnceocbiolncfljcmajijmeakcdlffnh" ascii wide
        $ext_252 = "domfmjgbmkckapepjahpedlpdedmckbj" ascii wide
        $ext_253 = "cbkogccidanmoaicgphipbdofakomlak" ascii wide
        $ext_254 = "bmlifknbfonkgphkpmkeoahgbhbdhebh" ascii wide
        $ext_255 = "ghaggkcfafofhcfppignflhlocmcfimd" ascii wide
        $ext_256 = "hfeialplaojonefabmojhobdmghnjkmf" ascii wide
        $ext_257 = "boiciofdokedkpmopjnghpkgdakmcpmb" ascii wide
        $ext_258 = "ibfpbjfnpcgmiggfildbcngccoomddmj" ascii wide
        $ext_259 = "idjhfmgaddmdojcfmhcjnnbhnhbmhipd" ascii wide
        $ext_260 = "jhgfinhjcamijjoikplacnfknpchndgb" ascii wide
        $ext_261 = "cgjgmbppcoolfkbkjhoogdpkboohhgel" ascii wide
        $ext_262 = "afooldonhjnhddgnfahlepchipjennab" ascii wide
        $ext_263 = "fkbcbgffcclobgbombinljckbelhnpif" ascii wide
        $ext_264 = "fpokgjmlcemklhmilomcljolhnbaaajk" ascii wide
        $ext_265 = "hadkldcldaanpomhhllacdmglkoepaed" ascii wide
        $ext_266 = "iedkeilnpbkeecjpmkelnglnjpnacnlh" ascii wide
        $ext_267 = "hjfmkkelabjoojjmjljidocklbibphgl" ascii wide
        $ext_268 = "dhjmmcjnajkpnbnbpagglbbfpbacoffm" ascii wide
        $ext_269 = "cgehahdmoijenmnhinajnojmmlnipckl" ascii wide
        $ext_270 = "fjigdpmfeomndepihcinokhcphdojepm" ascii wide
        $ext_271 = "chmcepembfffejphepoongapnlchjgil" ascii wide
        $ext_272 = "googojfbnbhbbnpfpdnffnklipgifngn" ascii wide
        $ext_273 = "fodcokjckpkfpegbekkiallamhedahjd" ascii wide
        $ext_274 = "igiakpjhacibmaichhgbagdkjmjbnanl" ascii wide
        $ext_275 = "omkjakddaeljdfgekdjebbbiboljnalk" ascii wide
        $ext_276 = "llilhpmmhicmiaoancaafdgganakopfg" ascii wide
        $ext_277 = "nemkiffjklgaooligallbpmhdmmhepll" ascii wide
        $ext_278 = "papedehkgfhnagdiempdbhlgcnioofnd" ascii wide
        $ext_279 = "glfddenhiaacfmhoiebfeljnfkkkmbjb" ascii wide
        $ext_280 = "pkjfghocapckmendmgdmppjccbplccbg" ascii wide
        $ext_281 = "gbcjipmcpedgndgdnfofbhgnkmghoamm" ascii wide
        $ext_282 = "ncapkionddmdmfocnjfcfpnimepibggf" ascii wide
        $ext_283 = "klggeioacnkkpdcnapgcoicnblliidmf" ascii wide
        $ext_284 = "klgjbnheihgnmimajhohfcldhfpjnahe" ascii wide
        $ext_285 = "acogeoajdpgplfhidldckbjkkpgeebod" ascii wide
        $ext_286 = "ekndlocgcngbpebppapnpalpjfnkoffh" ascii wide
        $ext_287 = "elckfehnjdbghpoheamjffpdbbogjhie" ascii wide
        $ext_288 = "dmpceopfiajfdnoiebfankfoabfehdpn" ascii wide
        $ext_289 = "gpolcigkhldaighngmmmcjldkkiaonbg" ascii wide
        $ext_290 = "dfakjobhimnibdmkbgpkijoihplhcnil" ascii wide
        $ext_291 = "hbghbdhfibifdgnbpaogepnkekonkdgc" ascii wide
        $ext_292 = "fppchnhginnfabgenhihpncnphhafmac" ascii wide
        $ext_293 = "ghhddclfklljabeodmcejjjlhoaaiban" ascii wide
        $ext_294 = "bppelgkcnhfkicolffhlkbdghdnjdkhi" ascii wide
        $ext_295 = "ikgaleggljchgbihlaanjbkekmmgccam" ascii wide
        $ext_296 = "bdhjinjoglaijpffoamhhnhooeimgoap" ascii wide
        $ext_297 = "fjioinpkgmlcioajfnncgldldcnabffe" ascii wide
        $ext_298 = "opncjjhgbllenobgbfjbblhghmdpmpbj" ascii wide
        $ext_299 = "cbijiaccpnkbdpgbmiiipedpepbhioel" ascii wide
        $ext_300 = "fbbmnieefocnacnecccgmedmcbhlkcpm" ascii wide
        $ext_301 = "hmbacpfgehmmoloinfmkgkpjoagiogai" ascii wide
        $ext_302 = "paghkadkhiladedijgodgghaajppmpcg" ascii wide
        $ext_303 = "bafbmfpfepdlgnfkgfbobplkkaoakjcl" ascii wide
        $ext_304 = "kcpkoopmfjhdpgjohcbgkbjpmbjmhgoi" ascii wide
        $ext_305 = "jelgelidmodjpmohbapbghdgcpncahki" ascii wide
        $ext_306 = "lfgakdlafdenmaikccbojgcofkkhmolj" ascii wide
        $ext_307 = "hdfknlljfbdfjdjhfgoonpphpigjjjak" ascii wide
        $ext_308 = "kpfbijpdidioaomoecdbfaodhajbcjfl" ascii wide
        $ext_309 = "fckphkcbpgmappcgnfieaacjbknhkhin" ascii wide
        $ext_310 = "lhfdakoonenpbggbeephofdlflloghhi" ascii wide
        $ext_311 = "ljjngehkphcdnnapgciajcdbcpgmpknc" ascii wide
        $ext_312 = "ejfocpkjndmkbloiobcdhkkoeekcpkik" ascii wide
        $ext_313 = "ccdimkoieijdbgdlkfjjfncmihmlpanj" ascii wide
        $ext_314 = "agdlpnhabjfcbeiempefhpgikapcapjb" ascii wide
        $ext_315 = "mddfnhdadbofiifdebeiegecchpkbgdb" ascii wide
        $ext_316 = "alknmfpopohfpdpafdmobclioihdkhjh" ascii wide
        $ext_317 = "hlglicejgohbanllnmnjllajhmnhjjel" ascii wide
        $ext_318 = "iaccapfapbjahnhcmkgjjonlccbhdpjl" ascii wide
        $ext_319 = "ehmnkbambjnodfbjcebjffilahbfjdml" ascii wide
        $ext_320 = "ngbfciefgjgijkkmpalnmhikoojilkob" ascii wide
        $ext_321 = "laholcgeblfbgdhkbiidbpiofdcbpeeo" ascii wide
        $ext_322 = "njoedigapanaggiabjafnaklppphempm" ascii wide
        $ext_323 = "fomlombffdkflbliepgpgcnagolnegjn" ascii wide
        $ext_324 = "jpoofbjomdefajdjcimmaoildecebkjc" ascii wide
        $ext_325 = "nhdiopbebcklbkpfnhipecgfhdhdbfhb" ascii wide
        $ext_326 = "gdnhikbabcflemolpeaaknnieodgpiie" ascii wide
        $ext_327 = "bbdioggpbhhodagchciaeaggdponnhpa" ascii wide
        $ext_328 = "ikajognfijokhbgjdhgpemljgcjclpmn" ascii wide
        $ext_329 = "lmnjiioclbjphkggicmldippjojgmldk" ascii wide
        $ext_330 = "ffgihbmcfcihmpbegcfdkmafaplheknk" ascii wide
        $ext_331 = "lgnjdldkappogbkljaiedgogobcgemch" ascii wide
        $ext_332 = "hiodlpcelfelhpinhgngoopbmclcaghd" ascii wide
        $ext_333 = "mnophppbmlnlfobakddidbcgcjakipin" ascii wide
        $ext_334 = "jbajdpebknffiaenkdhopebkolgdlfaf" ascii wide
        $ext_335 = "ejdihbblcbdfobabjfebfjfopenohbjb" ascii wide
        $ext_336 = "ikkoanocgpdmmiamnkogipbpdpckcahn" ascii wide
        $ext_337 = "ileojfedpkdbkcchpnghhaebfoimamop" ascii wide
        $ext_338 = "akialmafcdmkelghnomeneinkcllnoih" ascii wide
        $ext_339 = "eholblediahnodlgigdkdhkkpmbiafoj" ascii wide
        $ext_340 = "ipokalojgdmhfpagmhnjokidnpjfnfik" ascii wide
        $ext_341 = "hdpmmcmblgbkllldbccfdejchjlpochf" ascii wide
        $ext_342 = "iphacjobmeoknlhenjfiilbkddgaljad" ascii wide
        $ext_343 = "jiiggekklbbojgfmdenimcdkmidnfofl" ascii wide
        $ext_344 = "gkhggnaplpjkghjjcmpmnmidjndojpcn" ascii wide
        $ext_345 = "opakkgodhhongnhbdkgjgdlcbknacpaa" ascii wide
        $ext_346 = "nkjomoafjgemogbdkhledkoeaflnmgfi" ascii wide
        $ext_347 = "ebileebbekdcpfjlekjapgmbgpfigled" ascii wide
        $ext_348 = "oaacndacaoelmkhfilennooagoelpjop" ascii wide
        $ext_349 = "ljkgnegaajfacghepjiajibgdpfmcfip" ascii wide
        $ext_350 = "hgolomhkdcpmbgckhebdhdknaemlbbaa" ascii wide
        $ext_351 = "bboeoilakaofjkdmekpgeigieokkpgfn" ascii wide
        $ext_352 = "dkkpollfhjoiapcenojlmgempmjekcla" ascii wide
        $ext_353 = "emiocjgakibimbopobplmfldkldhhiad" ascii wide
        $ext_354 = "nchdmembkfgkejljapneliogidkchiop" ascii wide
        $ext_355 = "lljplndkobdgkjilfmfiefpldkhkhbbd" ascii wide
        $ext_356 = "hofaaigdagglolgiefkbencchnekjejl" ascii wide
        $ext_357 = "hohobnhiiohgcipklpncfmjkjpmejjni" ascii wide
        $ext_358 = "jocnjcakendmllafpmjailfnlndaaklf" ascii wide
        $ext_359 = "bjdclfjlhgcdcpjhmhfggkkfacipilai" ascii wide
        $ext_360 = "ahebpkbnckhgjmndfjejibjjahjdlhdb" ascii wide
        $ext_361 = "enaigkcpmpohpbokbfllbkijmllmpafm" ascii wide
        $ext_362 = "bpngofombcjloljkoafhmpcjclkekfbh" ascii wide
        $ext_363 = "cacbflgkiidgcekflfgdnjdnaalfmkob" ascii wide
        $ext_364 = "ibmgdfenfldppaodbahpgcoebmmkdbac" ascii wide
        $ext_365 = "deopfbighgnpgfmhjeccdifdmhcjckoe" ascii wide
        $ext_366 = "gcogpdjkkamgkakkjgeefgpcheonclca" ascii wide
        $ext_367 = "jckkfbfmofganecnnpfndfjifnimpcel" ascii wide
        $ext_368 = "nimlmejbmnecnaghgmbahmbaddhjbecg" ascii wide
        $ext_369 = "pphgdbgldlmicfdkhondlafkiomnelnk" ascii wide
        $ext_370 = "feflcgofneboehfdeebcfglbodaceghj" ascii wide
        $ext_371 = "almalgbpmcfpdaopimbdchdliminoign" ascii wide
        $ext_372 = "eppiocemhmnlbhjplcgkofciiegomcon" ascii wide
        $ext_373 = "inhcgfpbfdjbjogdfjbclgolkmhnooop" ascii wide
        $ext_374 = "fnmihdojmnkclgjpcoonokmkhjpjechg" ascii wide
        $ext_375 = "gaiceihehajjahakcglkhmdbbdclbnlf" ascii wide
        $ext_376 = "dpdibkjjgbaadnnjhkmmnenkmbnhpobj" ascii wide
        $ext_377 = "kgmeffmlnkfnjpgmdndccklfigfhajen" ascii wide
        $ext_378 = "mlgbkfnjdmaoldgagamcnommbbnhfnhf" ascii wide
        $ext_379 = "eckokfcjbjbgjifpcbdmengnabecdakp" ascii wide
        $ext_380 = "mgbhdehiapbjamfgekfpebmhmnmcmemg" ascii wide
        $ext_381 = "cbajickflblmpjodnjoldpiicfmecmif" ascii wide
        $ext_382 = "pdbfcnhlobhoahcamoefbfodpmklgmjm" ascii wide
        $ext_383 = "eokjikchkppnkdipbiggnmlkahcdkikp" ascii wide
        $ext_384 = "eokjikchkppnkdipbiggnmlkahcdkikp" ascii wide
        $ext_385 = "eokjikchkppnkdipbiggnmlkahcdkikp" ascii wide
        $ext_386 = "ihbiedpeaicgipncdnnkikeehnjiddck" ascii wide
        $ext_387 = "jjdajogomggcjifnjgkpghcijgkbcjdi" ascii wide
        $ext_388 = "mmcnmppeeghenglmidpmjkaiamcacmgm" ascii wide
        $ext_389 = "ojdkklpgpacpicaobnhankbalkkgaafp" ascii wide
        $ext_390 = "lodeighbngipjjedfelnboplhgediclp" ascii wide
        $ext_391 = "hkjagicdaogfgdifaklcgajmgefjllmd" ascii wide
        $ext_392 = "gflkbgebojohihfnnplhbdakoipdbpdm" ascii wide
        $ext_393 = "kpilmncnoafddjpnbhepaiilgkdcieaf" ascii wide
        $ext_394 = "caibdnkmpnjhjdfnomfhijhmebigcelo" ascii wide
        $ext_395 = "pdlmjggogjgoaifncfpkhldgfilgghgc" ascii wide
        $ext_396 = "niapdbllcanepiiimjjndipklodoedlc" ascii wide
        $ext_397 = "lgjdgmdbfhobkdbcjnpnlmhnplnidkkp" ascii wide
        $ext_398 = "chmfnmjfghjpdamlofhlonnnnokkpbao" ascii wide
        $ext_399 = "lklmhefoneonjalpjcnhaidnodopinib" ascii wide
        $ext_400 = "ciifcakemmcbbdpmljdohdmbodagmela" ascii wide
        $ext_401 = "meljmedplehjlnnaempfdoecookjenph" ascii wide
        $ext_402 = "lipmdblppejomolopniipdjlpfjcojob" ascii wide
        $ext_403 = "lmcboojgmmaafdmgacncdpjnpnnhpmei" ascii wide
        $ext_404 = "icnekagcncdgpdnpoecofjinkplbnocm" ascii wide
        $ext_405 = "bahogceckgcanpcoabcdgmoidngedmfo" ascii wide
        $ext_406 = "bkpdalonclochcahhipekbnedhklcdnp" ascii wide
        $ext_407 = "magnkhldhhgdlhikeighmhlhonpmlolk" ascii wide
        $ext_408 = "edadmcnnkkkgmofibeehgaffppadbnbi" ascii wide
        $ext_409 = "ajneghihjbebmnljfhlpdmjjpifeaokc" ascii wide
        $ext_410 = "nadenkhojomjfdcppbhhncbfakfjiabp" ascii wide
        $ext_411 = "pbdpfhmbdldfoioggnphkiocpidecmbp" ascii wide
        $ext_412 = "hdgdghnfcappcodemanhafioghjhlbpb" ascii wide
        $ext_413 = "fbjfihoienmhbjflbobnmimfijpngkpa" ascii wide
        $ext_414 = "kjeffohcijbnlkgoaibmdcfconakaajm" ascii wide
        $ext_415 = "djmpbcihmblfdlkcfncodakgopmpgpgh" ascii wide
        $ext_416 = "obeokabcpoilgegepbhlcleanmpgkhcp" ascii wide
        $ext_417 = "mcmdolplhpeopapnlpbjceoofpgmkahc" ascii wide
        $ext_418 = "dppnhoaonckcimpejpjodcdoenfjleme" ascii wide
        $ext_419 = "idgncaddojiejegdmkofblgplkgmeipk" ascii wide
        $ext_420 = "deebfeldnfhemlnidojiiidadkgnglpi" ascii wide
        $ext_421 = "gfbgiekofllpkpaoadjhbbfnljbcimoh" ascii wide
        $ext_422 = "pbebadpeajadcmaoofljnnfgofehnpeo" ascii wide
        $ext_423 = "flmihfcdcgigpfcfjpdcniidbfnffdcf" ascii wide
        $ext_424 = "pinnfpbpjancnbidnnhpemakncopaega" ascii wide
        $ext_425 = "iicpikopjmmincpjkckdngpkmlcchold" ascii wide
        $ext_426 = "bjlcpoknpgaoaollojjdnbdojdclidkh" ascii wide
        $ext_427 = "okclicinnbnfkgchommiamjnkjcibfid" ascii wide
        $ext_428 = "pcjmcnhpobkjnhajhhleejfmpeoahclc" ascii wide
        $ext_429 = "hinhmojdkodmficpockledafoeodokmc" ascii wide
        $ext_430 = "gcnceeflimggoamelclcbhcdggcmnglm" ascii wide
        $ext_431 = "kacljcbejojnapnmiifgckbafkojcncf" ascii wide
        $ext_432 = "jhkhlgaomejplkanglolfpcmfknnomle" ascii wide
        $ext_433 = "nkmooloiipfcknccapehflmampkaniji" ascii wide
        $ext_434 = "kgddnoifhgfdhcpbkkjdgokfnkkmdcen" ascii wide
        $ext_435 = "gbdjcgalliefpinpmggefbloehmmknca" ascii wide
        $ext_436 = "eggeoellnjnnglaibpcmggjnjifeebpi" ascii wide
        $ext_437 = "ionpbgeeliajehajombdeflogfpgmmel" ascii wide
        $ext_438 = "jaekigmcljkkalnicnjoafgfjoefkpeg" ascii wide
        $ext_439 = "aeilijiaejfdnbagnpannhdoaljpkbhe" ascii wide
        $ext_440 = "afdfpkhbdpioonfeknablodaejkklbdn" ascii wide
        $ext_441 = "anflghppebdhjipndogapfagemgnlblh" ascii wide
        $ext_442 = "anmbbeeiaollmpadookgoakpfjkbidaf" ascii wide
        $ext_443 = "bebmphofpgkhclocdbgomhnjcpelbenh" ascii wide
        $ext_444 = "bmkgbgkneealfabgnjfeljaiegpginpl" ascii wide
        $ext_445 = "ccjlpblmgkncnnimcmbanbnhbggdpkie" ascii wide
        $ext_446 = "cclhgechkjghfaoebihpklmllnnlnbdb" ascii wide
        $ext_447 = "cfegchignldpfnjpodhcklmgleaoanhi" ascii wide
        $ext_448 = "cfllfglbkmnbkcibbjoghimalbileaic" ascii wide
        $ext_449 = "cjljdgfhkjbdbkcdkfojleidpldagmao" ascii wide
        $ext_450 = "coabfkgengacobjpmdlmmihhhfnhbjdm" ascii wide
        $ext_451 = "dcaffjpclkkjfacgfofgpjbmgjnjlpmh" ascii wide
        $ext_452 = "djekgpcemgcnfkjldcclcpcjhemofcib" ascii wide
        $ext_453 = "dkbccihpiccbcheieabdbjikohfdfaje" ascii wide
        $ext_454 = "dlpimjmonhbmamocpboifndnnakgknbf" ascii wide
        $ext_455 = "dmbjkidogjmmlejdmnecpmfapdmidfjg" ascii wide
        $ext_456 = "dneifdhdmnmmlobjbimlkcnhkbidmlek" ascii wide
        $ext_457 = "doiiaejbgndnnnomcdhefcbfnbbjfbib" ascii wide
        $ext_458 = "dpfofggmkhdbfcciajfdphofclabnogo" ascii wide
        $ext_459 = "eabhkjojehdleajkbigffmpnaelncapp" ascii wide
        $ext_460 = "ealojglnbikknifbgleaceopepceakfn" ascii wide
        $ext_461 = "ebdbcfomjliacpblnioignhfhjeajpch" ascii wide
        $ext_462 = "edlifbnjlicfpckhgjhflgkeeibhhcii" ascii wide
        $ext_463 = "ehmneimbopigfgchjglgngamiccjkijh" ascii wide
        $ext_464 = "ehpgcagmhpndkmglombjndkdmggkgnge" ascii wide
        $ext_465 = "ejllkedmklophclpgonojjkaliafeilj" ascii wide
        $ext_466 = "ekjogkoigkhbgdgpolejnjfmhdcgaoof" ascii wide
        $ext_467 = "elpdbicokgbedckgblmbhoamophfbchi" ascii wide
        $ext_468 = "emeokgokialpjadjaoeiplmnkjoaegng" ascii wide
        $ext_469 = "eokjikchkppnkdipbiggnmlkahcdkikp" ascii wide
        $ext_470 = "epeigjgefhajkiiallmfblgglmdbhfab" ascii wide
        $ext_471 = "eplfglplnlljjpeiccbgnijecmkeimed" ascii wide
        $ext_472 = "fbbjijdngocdplimineplmdllhjkaece" ascii wide
        $ext_473 = "fbjhgeaafhlbjiejehpjdnghinlcceak" ascii wide
        $ext_474 = "fedchalbmgfhdobblebblldiblbmpgdj" ascii wide
        $ext_475 = "fobaamfiblkoobhjpiigemmdegbmpohd" ascii wide
        $ext_476 = "gaiceihehajjahakcglkhmdbbdclbnlf" ascii wide
        $ext_477 = "gceehiicnbpehbbdaloolaanlnddailm" ascii wide
        $ext_478 = "ggacghlcchiiejclfdajbpkbjfgjhfol" ascii wide
        $ext_479 = "gjjbmfigjpgnehjioicaalopaikcnheo" ascii wide
        $ext_480 = "gpdfpljioapjogbnlpmganakfjcemifk" ascii wide
        $ext_481 = "hjlekdknhjogancdagnndeenmobeofgm" ascii wide
        $ext_482 = "hlbdhflagoegglpdminhlpenkdgloabe" ascii wide
        $ext_483 = "hnfabcchmopgohnhkcojhocneefbnffg" ascii wide
        $ext_484 = "iabflonngmpkalkpbjonemaamlgdghea" ascii wide
        $ext_485 = "ibppednjgooiepmkgdcoppnmbhmieefh" ascii wide
        $ext_486 = "icchadngbpkcegnabnabhkjkfkfflmpj" ascii wide
        $ext_487 = "ielooaepfhfcnmihgnabkldnpddnnldl" ascii wide
        $ext_488 = "ifdepgnnjpnbkcgempionjablajancjc" ascii wide
        $ext_489 = "ijejnggjjphlenbhmjhhgcdpehhacaal" ascii wide
        $ext_490 = "iklgljbighkgbjoecoddejooldolenbj" ascii wide
        $ext_491 = "imopknpgdihifjkjpmjaagcagkefddnb" ascii wide
        $ext_492 = "jchmabokofdoabocpiicjljelmackhho" ascii wide
        $ext_493 = "jdlkkmamiaikhfampledjnhhkbeifokk" ascii wide
        $ext_494 = "jglemppahimembneahjbkhjknnefeeio" ascii wide
        $ext_495 = "jiaopkfkampgnnkckajcbdgannoipcne" ascii wide
        $ext_496 = "jjgnkfncaadmaobenjjpmngdpgalemho" ascii wide
        $ext_497 = "jlbpahgopcmomkgegpbmopfodolajhbl" ascii wide
        $ext_498 = "jpefmbpcbebpjpmelobfakahfdcgcmkl" ascii wide
        $ext_499 = "khdnaopfklkdcloiinccnaflffmfcioa" ascii wide
        $ext_500 = "kjgkmceledmpdnmgmppiekdbnamccdjp" ascii wide
        $ext_501 = "laameccjpleogmfhilmffpdbiibgbekf" ascii wide
        $ext_502 = "lagdcjmbchphhndlbpfajelapcodekll" ascii wide
        $ext_503 = "lbohagbplppjcpllnhdichjldhfgkicb" ascii wide
        $ext_504 = "ledkggjjapdgojgihnaploncccgiadhg" ascii wide
        $ext_505 = "lgecddhfcfhlmllljooldkbbijdcnlpe" ascii wide
        $ext_506 = "lkahpjghmdhpiojknppmlenngmpkkfma" ascii wide
        $ext_507 = "lkciiknpgglgbbcgcpbpobjabglmpkle" ascii wide
        $ext_508 = "lkhhagecaghfakddbncibijbjmgfhfdm" ascii wide
        $ext_509 = "lknpbgnookklokdjomiildnlalffjmma" ascii wide
        $ext_510 = "lojpdfjjionbhgplcangflkalmiadhfi" ascii wide
        $ext_511 = "mdkiofbiinbmlblcfhfjgmclhdfikkpm" ascii wide
        $ext_512 = "meffljleomgifbbcffejnmhjagncfpbd" ascii wide
        $ext_513 = "mejjgaogggabifjfjdbnobinfibaamla" ascii wide
        $ext_514 = "mhpcabliilgadobjpkameggapnpeppdg" ascii wide
        $ext_515 = "mkjjckchdfhjbpckippbnipkdnlidbeb" ascii wide
        $ext_516 = "mldaiedoebimcgkokmknonjefkionldi" ascii wide
        $ext_517 = "mlkjjjmhjijlmafgjlpkiobpdocdbncj" ascii wide
        $ext_518 = "mndiaaeaiclnmjcnacogaacoejchdclp" ascii wide
        $ext_519 = "mnlohknjofogcljbcknkakphddjpijak" ascii wide
        $ext_520 = "nhnfcgpcbfclhfafjlooihdfghaeinfc" ascii wide
        $ext_521 = "ninecedhhpccjifamhafbdelibdjibgd" ascii wide
        $ext_522 = "nmigaijibiabddkkmjhlehchpmgbokfj" ascii wide
        $ext_523 = "npdkkcjlmhcnnaoobfdjndibfkkhhdfn" ascii wide
        $ext_524 = "npmjjkphdlmbeidbdbfefgedondknlaf" ascii wide
        $ext_525 = "oakbcaafbicdddpdlhbchhpblmhefngh" ascii wide
        $ext_526 = "obdhcplpbliifflekgclobogbdliddjd" ascii wide
        $ext_527 = "ocginjipilabheemhfbedijlhajbcabh" ascii wide
        $ext_528 = "oepjogknopbbibcjcojmedaepolkghpb" ascii wide
        $ext_529 = "ofpnikijgfhlmmjlpkfaifhhdonchhoi" ascii wide
        $ext_530 = "ogadflejmplcdhcldlloonbiekhnlopp" ascii wide
        $ext_531 = "ogfjgagnmkiigilnoiabkbbajinanlbn" ascii wide
        $ext_532 = "okkffdhbfplmbjblhgapnchjinanmnij" ascii wide
        $ext_533 = "oodkhhminilgphkdofffddlgopkgbgpm" ascii wide
        $ext_534 = "pegfdldddiilihjahcpdehhhfcbibipg" ascii wide
        $ext_535 = "phfkifnjcmdcmljnnablahicoabkokbg" ascii wide
        $ext_536 = "phjbepamfhjgjdgmbhmfflhnlohldchb" ascii wide
        $ext_537 = "pjbgfifennfhnbkhoidkdchbflppjncb" ascii wide
        $ext_538 = "plmlopfeeobajiecodiggabcihohcnge" ascii wide
        $ext_539 = "pmilcmjbofinpnbnpanpdadijibcgifc" ascii wide
        $ext_540 = "pmnphobdokkajkpbkajlaiooipfcpgio" ascii wide
        $ext_541 = "pnanegnllonoiklmmlegcaajoicfifcm" ascii wide
        $ext_542 = "pnlphjjfielecalmmjjdhjjninkbjdod" ascii wide
        $ext_543 = "pooaemmkohlphkekccfajnbcokjlbehk" ascii wide
        $ext_544 = "fmlpbbognkocpajihchioognkmdeeldo" ascii wide
        $ext_545 = "goaebigflkhjjblmofhoggdhebgnielo" ascii wide
        $ext_546 = "igkkmokkmlbkkgdnkkancbonkbbmkioc" ascii wide
        $ext_547 = "lopnbnfpjmgpbppclhclehhgafnifija" ascii wide
        $ext_548 = "kgfeiebnfmmfpomhochmlfmdmjmfedfj" ascii wide
        $ext_549 = "pmlcjncilaaaemknfefmegedhcgelmee" ascii wide
        $ext_550 = "ohdgnoepeabcfdkboidmaedenahioohf" ascii wide
        $ext_551 = "dnbipceilikdgjmeiagblfckeialaela" ascii wide
        $ext_552 = "aciipkgmbljbcokcnhjbjdhilpngemnj" ascii wide
        $ext_553 = "nlmjpeojbncdmlfkpppngdnolhfgiehn" ascii wide
        $ext_554 = "phjhbkdgnjaokligmkimgnlagccanodn" ascii wide
        $ext_555 = "fkhpfgpmejefmjaeelgoopkcglgafedm" ascii wide
        $ext_556 = "kekdpkbijjffmohdaonbpeeaiknhbkhj" ascii wide
        $ext_557 = "mcmmiinopedfbaoongoclagidncaacbd" ascii wide
        $ext_558 = "ndcokkmfmiaecmndbpohaogmpmchfpkk" ascii wide
        $ext_559 = "cpmpjapeeidaikiiemnddfgfdfjjhgif" ascii wide
        $ext_560 = "ajefbooiifdkmgkpjkanmgbjbndfbfhg" ascii wide
        $ext_561 = "acmnokigkgihogfbeooklgemindnbine" ascii wide
        $ext_562 = "apgohnlmnmkblgfplgnlmkjcpocgfomp" ascii wide
        $ext_563 = "apjnadhmhgdobcdanndaphcpmnjbnfng" ascii wide
        $ext_564 = "bahkljhhdeciiaodlkppoonappfnheoi" ascii wide
        $ext_565 = "bannaglhmenocdjcmlkhkcciioaepfpj" ascii wide
        $ext_566 = "bgffinjklipdhacmidehoncomokcmjmh" ascii wide
        $ext_567 = "bifdhahddjbdbjmiekcnmeiffabcfjgh" ascii wide
        $ext_568 = "bjpknhldlbknoidifkjnnkpginjgkgnm" ascii wide
        $ext_569 = "blngdeeenccpfjbkolalandfmiinhkak" ascii wide
        $ext_570 = "ccdfhjebekpopcelcfkpgagbehppkadi" ascii wide
        $ext_571 = "cceejgojinihpakmciijfdgafhpchigo" ascii wide
        $ext_572 = "cebjhmljaodmgmcaecenghhikkjdfabo" ascii wide
        $ext_573 = "chbpnonhcgdbcpicacolalkgjlcjkbbd" ascii wide
        $ext_574 = "cifafogcmckphmnbeipgkpfbjphmajbc" ascii wide
        $ext_575 = "clopbiaijcfolfmjebjinippgmdkkppj" ascii wide
        $ext_576 = "cpgoblgcfemdmaolmfhpoifikehgbjbf" ascii wide
        $ext_577 = "dcmjopnlojhkngkmagminjbiahokmfig" ascii wide
        $ext_578 = "deiiiklocnibjflinkfmefpofgcfhdga" ascii wide
        $ext_579 = "dipecofobdcjnpffbkmfkdbfmjfjfgmn" ascii wide
        $ext_580 = "dopkmmcoegcjggfanajnindneifffpck" ascii wide
        $ext_581 = "dopmojabcdlfbnppmjeaajclohofnbol" ascii wide
        $ext_582 = "edcepmkpdojmciieeijebkodahjfliif" ascii wide
        $ext_583 = "ekbecnhekcpbfgdchfjcfmnocdfpcanj" ascii wide
        $ext_584 = "elflophcopcglipligoibfejllmndhmp" ascii wide
        $ext_585 = "eogfeijdemimhpfhlpjoifeckijeejkc" ascii wide
        $ext_586 = "fcobokliblbalmjmahdebcdalglnieii" ascii wide
        $ext_587 = "fgafnjobnempajahhgebbbpkpegcdlbf" ascii wide
        $ext_588 = "fgcomdacecoimaejookmlcfogngmfmli" ascii wide
        $ext_589 = "fgmeppijnhhafacemgoocgelcflipnfd" ascii wide
        $ext_590 = "fhanjgcjamaagccdkanegeefdpdkeban" ascii wide
        $ext_591 = "flfkimeelfnpapcgmobfgfifhackkend" ascii wide
        $ext_592 = "fmahbaepkpdimfcjpopjklankbbhdobk" ascii wide
        $ext_593 = "foebfmkeamadbhjcdglihfijdaohomlm" ascii wide
        $ext_594 = "fpngnlpmkfkhodklbljnncdcmkiopide" ascii wide
        $ext_595 = "gdifegeihkihjbkkgdijkcpkjekoicbl" ascii wide
        $ext_596 = "gfcmbgjehfhemioddkpcipehdfnjmief" ascii wide
        $ext_597 = "gfdefkjpjdbiiclhimebabkmclmiiegk" ascii wide
        $ext_598 = "ggijmaajgdkdijomfipnpdfijcnodpip" ascii wide
        $ext_599 = "ghgjhnkjohlnmngbniijbkidigifekaa" ascii wide
        $ext_600 = "gllihgnfnbpdmnppfjdlkciijkddfohn" ascii wide
        $ext_601 = "gmmohhcojdhgbjjahhpkfhbapgcfgfne" ascii wide
        $ext_602 = "gofhadkfcffpjdbonbladicjdbkpickk" ascii wide
        $ext_603 = "hapicipmkalhnklammmfdblkngahelln" ascii wide
        $ext_604 = "hijipblimhboccjcnnjnjelcdmceeafa" ascii wide
        $ext_605 = "hmamdkecijcegebmhndhcihjjkndbjgk" ascii wide
        $ext_606 = "hodfejbmfdhcgolcglcojkpfdjjdepji" ascii wide
        $ext_607 = "hpfijbjnmddglpmogpaeofdbehkpball" ascii wide
        $ext_608 = "ianfonfnhjeidghdegbkbbjgliiciiic" ascii wide
        $ext_609 = "ibfjiddieiljjjccjemgnoopkpmpniej" ascii wide
        $ext_610 = "inhdgbalcopmbpjfincjponejamhaeop" ascii wide
        $ext_611 = "iondldgmpaoekbgabgconiajpbkebkin" ascii wide
        $ext_612 = "ipagcbjbgailmjeaojmpiddflpbgjngl" ascii wide
        $ext_613 = "jagbooldjnemiedoagckjomjegkopfno" ascii wide
        $ext_614 = "jdheollkkpfglhohnpgkonecdealeebn" ascii wide
        $ext_615 = "jfefcmidfkpncdkjkkghhmjkafanhiam" ascii wide
        $ext_616 = "jfgkpeobcmjlocjpfgocelimhppdmigj" ascii wide
        $ext_617 = "jghiljaagglmcdeopnjkfhcikjnddhhc" ascii wide
        $ext_618 = "jgjakaebbliafihodjhpkpankimhckdf" ascii wide
        $ext_619 = "jiiinmeiedloeiabcgkdcbbpfelmbaff" ascii wide
        $ext_620 = "jkdngiblfdmfjhiahibnnhcjncehcgab" ascii wide
        $ext_621 = "jkofpdjclecgjcfomkaajhhmmhnninia" ascii wide
        $ext_622 = "kbdbmddhlgckaggdapibpihadohhelao" ascii wide
        $ext_623 = "keceijnpfmmlnebgnkhojinbkopolaom" ascii wide
        $ext_624 = "khhemdcdllgomlbleegjdpbeflgbomcj" ascii wide
        $ext_625 = "kjdcopljcgiekkmjhinmcpioncofoclg" ascii wide
        $ext_626 = "kjgaljeofmfgjfipajjeeflbknekghma" ascii wide
        $ext_627 = "labpefoeghdmpbfijhnnejdmnjccgplc" ascii wide
        $ext_628 = "lameokaalbmnhgapanlloeichlbjloak" ascii wide
        $ext_629 = "lbeekfefglldjjenkaekhnogoplpmfin" ascii wide
        $ext_630 = "lbhddhdfbcdcfbbbmimncbakkjobaedh" ascii wide
        $ext_631 = "ldoiiiffclpggehajofeffljablcodif" ascii wide
        $ext_632 = "lhjdepbplpkgmghgiphdjpnagpmhijbg" ascii wide
        $ext_633 = "ljddilebjpmmomoppeemckhpilhmoaok" ascii wide
        $ext_634 = "ljnfpiodfojmjfbiechgkbkhikfbknjc" ascii wide
        $ext_635 = "lnedcnepmplnjmfdiclhbfhneconamoj" ascii wide
        $ext_636 = "lnlkgfpceclfhomgocnnenmadlhanghf" ascii wide
        $ext_637 = "loigeafmbglngofpkkddgobapkkcaena" ascii wide
        $ext_638 = "lpajppfbbiafpmbeompbinpigbemekcg" ascii wide
        $ext_639 = "majekhlfhmeeplofdolkddbecmgjgplm" ascii wide
        $ext_640 = "mapafdeimlgplbahigmhneiibemhgcnc" ascii wide
        $ext_641 = "mcfeaailfhmpdphgnheboncfiikfkenn" ascii wide
        $ext_642 = "mgkjakldpclhkfadefnoncnjkiaffpkp" ascii wide
        $ext_643 = "mhinpnedhapjlbgnhcifjdkklbeefbpa" ascii wide
        $ext_644 = "mihiainclhehjnklijgpokdpldjmjdap" ascii wide
        $ext_645 = "mmkakbkmcnchdopphcbphjioggaanmim" ascii wide
        $ext_646 = "mopkkgobjofbkkgemcidkndbglkcfhjj" ascii wide
        $ext_647 = "mpifmhgignilkmeckejgamolchmgfdom" ascii wide
        $ext_648 = "nabmpeienmkmicpjckkgihobgleppbkc" ascii wide
        $ext_649 = "nahhmpbckpgdidfnmfkfgiflpjijilce" ascii wide
        $ext_650 = "ncepfbpjhkahgdemgmjmcgbgnfdinnhk" ascii wide
        $ext_651 = "npaklgbiblcbpokaiddpmmbknncnbljb" ascii wide
        $ext_652 = "npdfkclmbnoklkdebjfodpendkepbjek" ascii wide
        $ext_653 = "nplenkhhmalidgamfdejkblbaihndkcm" ascii wide
        $ext_654 = "oalfdomffplbcimjikgaklfamodahpmi" ascii wide
        $ext_655 = "odnakbaioopckimfnkllgijmkikhfhhf" ascii wide
        $ext_656 = "oklejhdbgggnfaggiidiaokelehcfjdp" ascii wide
        $ext_657 = "omgeapkgiddakeoklcapboapbamdgmhp" ascii wide
        $ext_658 = "oonbcpdabjcggcklopgbdagbfnkhbgbe" ascii wide
        $ext_659 = "opahibnipmkjincplepgjiiinbfmppmh" ascii wide
        $ext_660 = "pamchlfnkebmjbfbknoclehcpfclbhpl" ascii wide
        $ext_661 = "pcfapghfanllmbdfiipeiihpkojekckk" ascii wide
        $ext_662 = "pchfjdkempbhcjdifpfphmgdmnmadgce" ascii wide
        $ext_663 = "pdpcpceofkopegffcdnffeenbfdldock" ascii wide
        $ext_664 = "pgahbiaijngfmbbijfgmchcnkipajgha" ascii wide
        $ext_665 = "pidohlmjfgjbafgfleommlolmbjdcpal" ascii wide
        $ext_666 = "pilplloabdedfmialnfchjomjmpjcoej" ascii wide
        $ext_667 = "pklmnoldkkoholegljdkibjjhmegpjep" ascii wide
        $ext_668 = "pknkncdfjlncijifekldbjmeaiakdbof" ascii wide
        $ext_669 = "plmgefkiicjfchonlmnbabfebpnpckkk" ascii wide
        $ext_670 = "pnciakodcdnehobpfcjcnnlcpmjlpkac" ascii wide
        $ext_671 = "ponodoigcmkglddlljanchegmkgkhmgb" ascii wide
        $ext_672 = "oanbpfkcehelcjjipodkaafialmfejmi" ascii wide
        $ext_673 = "lhfibgclamcffnddoicjmoopmgomknmb" ascii wide
        $ext_674 = "ilcbbngkolbclhlildojhgjdbkkehfia" ascii wide
        $ext_675 = "pnhjnmacgahapmnnifmneapinilajfol" ascii wide
        $ext_676 = "ocifcogajbgikalbpphmoedjlcfjkhgh" ascii wide
        $ext_677 = "peglehonblabfemopkgmfcpofbchegcl" ascii wide
        $ext_678 = "aaeohfpkhojgdhocdfpkdaffbehjbmmd" ascii wide
        $ext_679 = "lidnmohoigekohfmdpopgcpigjkpemll" ascii wide
        $ext_680 = "jmbmildjdmppofnohldicmnkojfhggmb" ascii wide
        $ext_681 = "jdoaaldnifinadckcbfkbiekgaebkeif" ascii wide
        $ext_682 = "ogjfhmgoalinegalajpmjoliipdibhdm" ascii wide
        $ext_683 = "lebmkjafnodbnhbahbgdollaaabcmpbh" ascii wide
        $ext_684 = "gjammdgdlgmoidmdfoefkeklnhmllpjp" ascii wide
        $ext_685 = "kdkpllchojjkbgephbbeacaahecgfpga" ascii wide
        $ext_686 = "jaehldonmiabhfohkenmlimnceapgpnp" ascii wide
        $ext_687 = "pmhlkgkblgeeigiegkmacefjoflennbn" ascii wide
        $ext_688 = "ofdfbeanbffehepagohhengmjnhlkich" ascii wide
        $ext_689 = "mjchijabihjkhmmaaihpgmhkklgakinl" ascii wide
        $ext_690 = "poppendnaoonepbkmjejdfebihohaalo" ascii wide
        $ext_691 = "eogoljjmndnjfikmcbmopmlhjnhbmdda" ascii wide
        $ext_692 = "gdnkjjhpffldmfljpbfemliidkeeecdj" ascii wide
        $ext_693 = "gelcjfdfebnabkielednfoogpbhdeoai" ascii wide
        $ext_694 = "ofpihhkeakgnnbkmcoifjkkhnllddbld" ascii wide
        $ext_695 = "pjjghngpidphgicpgdebpmdgdicepege" ascii wide
        $ext_696 = "nchdkdaknojhpimbfbejfcdnmjfbllhj" ascii wide
        $ext_697 = "blcfpeooekoekehdpbikibeblpjlehlh" ascii wide
        $ext_698 = "looclnmoilplejheganiloofamfilbcd" ascii wide
        $ext_699 = "oehimkphpeeeneindfeekidpmkpffkgc" ascii wide
        $ext_700 = "eebbihndkbkejmlgfoofigacgicamfha" ascii wide
        $ext_701 = "faopefnnleiebimhkldlplkgkjpbmcea" ascii wide
        $ext_702 = "obcfkcpejehknjdollnafpebkcpkklbl" ascii wide
        $ext_703 = "jepocknhdcgdmbiodbpopcbjnlgecdhf" ascii wide
        $ext_704 = "dehhfjanlmglmabomenmpjnnopigplae" ascii wide
        $ext_705 = "ekijhekekfckmkmbemiijdkihdibnbgh" ascii wide
        $ext_706 = "pjpjefgijnjlhgegceegmpecklonpdjp" ascii wide
        $ext_707 = "nlhocomjnfjedielocojomgfldbjmdjj" ascii wide
        $ext_708 = "opooaebceonakifaacigffdhogdgfadg" ascii wide
        $ext_709 = "ojofdaokgfdlbeomlelkiiipkocneien" ascii wide
        $ext_710 = "gpaaalbnkccgmmbkendiciheljgpdhob" ascii wide
        $ext_711 = "almfnpjmjpnknlgpipillhfmchjikkno" ascii wide
        $ext_712 = "eeacchjlmkcleifpppcjbmahcnlihamj" ascii wide
        $ext_713 = "lojgkcienjoiogbfkbjiidpfnabhkckf" ascii wide
        $ext_714 = "gkemhapalomnipjhminflfhjcjehjhmp" ascii wide
        $ext_715 = "icolkoeolaodpjogekifcidcdbgbdobc" ascii wide
        $ext_716 = "abjbfhcehjndcpbiiagdnlfolkbfblpb" ascii wide
        $ext_717 = "bbjilncoookdcjjnkcdaofiollndepla" ascii wide
        $ext_718 = "igpcgjcdhmdjhdlgoncfnpkdipanlida" ascii wide
        $ext_719 = "nfhpojfdhcdmimokleagkdcbkmcgfjkh" ascii wide
        $ext_720 = "jfnlkmaledafkdhdokgnhlcmeamakham" ascii wide
        $ext_721 = "dibjpjiifnahccnokciamjlfgdlgimmn" ascii wide
        $ext_722 = "fjclfmhapndgeabdcikbhemimpijpnah" ascii wide
        $ext_723 = "jpnamljnefhpbpcofcbonjjjkmfjbhdp" ascii wide
        $ext_724 = "iggmbfojpkfikoahlfghaalpbpkhfohc" ascii wide
        $ext_725 = "fkllfgoempnigpogkgkgmghkchmjcjni" ascii wide
        $ext_726 = "dealfjgnmkibkcldkcpbikenmajlglmc" ascii wide
        $ext_727 = "abghmipjfclfpgmmelbgolfgmhnigbma" ascii wide
        $ext_728 = "dcbfmglfdlgpnolgdjoioeocllioebpe" ascii wide
        $ext_729 = "obmbmalbahpfbckpcfbipooimkldgphm" ascii wide
        $ext_730 = "gbkmkgfjngebdcpklbkeccelcjaobblk" ascii wide
        $ext_731 = "ehibgcefkpbfkklbpahilhicidnhiboc" ascii wide
        $ext_732 = "gmljddfeipofcffbhhcpohkegndieeab" ascii wide
        $ext_733 = "dajgdhiemoaecngkpliephmheifopmjb" ascii wide
        $ext_734 = "fdbmoflclpmkmeobidcgmfamkicinnlg" ascii wide
        $ext_735 = "obbfndpanmiplgfcbeonoocobbnjdmdc" ascii wide
        $ext_736 = "lgljionbhcfbnpjgfnhhoadpdngkmfnh" ascii wide
        $ext_737 = "ddenjpheppdmfimooolgihimdgpilhfo" ascii wide
        $ext_738 = "bblkckhknhmalchbceidkmjalmcmnkfa" ascii wide
        $ext_739 = "fhkmacopackahlbnpcfijgphgoimpggb" ascii wide
        $ext_740 = "eohnfgagodblipmmalphhfepaonpnjgk" ascii wide
        $ext_741 = "emkkigmmpfbjmikfadmfeebomholoikg" ascii wide
        $ext_742 = "fekjbjbbdopogpamkmdjpjicapclgamj" ascii wide
        $ext_743 = "afephhbbcdlgdehhddfnehfndnkfbgnm" ascii wide
        $ext_744 = "agfjbfkpehcnceblmdahjaejpnnnkjdn" ascii wide
        $ext_745 = "ahikdohkiedoomaklnohgdnmfcmbabcn" ascii wide
        $ext_746 = "ahlfiinafajfmciaajgophipcfholmeh" ascii wide
        $ext_747 = "akglkgdiggmkilkhejagginkngocbpbj" ascii wide
        $ext_748 = "anihmmejabpaocacmeodiapbhpholaom" ascii wide
        $ext_749 = "bhkcgfbaokmhglgipbppoobmoblcomhh" ascii wide
        $ext_750 = "bkanfnnhokogflpnhnbfjdhbjdlgncdi" ascii wide
        $ext_751 = "bpfdhglfmfepjhgnhnmclbfiknjnfblb" ascii wide
        $ext_752 = "bpklfenmjhcjlocdicfadpfppcgojfjp" ascii wide
        $ext_753 = "ckelhijilmmlmnaljmjpigfopkmfkoeh" ascii wide
        $ext_754 = "dbcfhcelmjepboabieglhjejeolaopdl" ascii wide
        $ext_755 = "dbcfokmgampdedgcefjahloodbgakkpl" ascii wide
        $ext_756 = "ddohdfnenhipnhnbbfifknnhaomihcip" ascii wide
        $ext_757 = "dehindejipifeaikcgbkdijgkbjliojc" ascii wide
        $ext_758 = "dkhcmjfipgoapjamnngolidbcakpdhgf" ascii wide
        $ext_759 = "effhjobodhmkbgfpgcdabfnjlnphakhb" ascii wide
        $ext_760 = "egpnofbhgafhbkapdhedimohmainbiio" ascii wide
        $ext_761 = "ehlgimmlmmcocemjadeafmohiplmgmei" ascii wide
        $ext_762 = "epphnioigompfjaknnaokghgcncnjfbe" ascii wide
        $ext_763 = "gbbpilgcdcmfppjkdociebhmcnbfbmod" ascii wide
        $ext_764 = "glmbceclkhkaebcadgmbcjihllcnpmjh" ascii wide
        $ext_765 = "gpffceikmehgifkjjginoibpceadefih" ascii wide
        $ext_766 = "idnelecdpebmbpnmambnpcjogingdfco" ascii wide
        $ext_767 = "ifceimlckdanenfkfoomccpcpemphlbg" ascii wide
        $ext_768 = "ifmkfoeijeemajoodjfoagpbejmmnkhm" ascii wide
        $ext_769 = "igkljanmhbnhedgkmgpkcgpjmociceim" ascii wide
        $ext_770 = "ijhakgidfnlallpobldpbhandllbeobg" ascii wide
        $ext_771 = "ijohicfhndicpnmkaldafhbecijhdikd" ascii wide
        $ext_772 = "jbfponbaiamgjmfpfghcjjhddjdjdpna" ascii wide
        $ext_773 = "jfamimfejiccpbnghhjfcibhkgblmiml" ascii wide
        $ext_774 = "jlaaidmjgpgfkhehcljmeckhlaibgaol" ascii wide
        $ext_775 = "kjnmimfgphmcppjhombdhhegpjphpiol" ascii wide
        $ext_776 = "lfaahmcgahoalphllknbfcckggddoffj" ascii wide
        $ext_777 = "mcbcknmlpfkbpogpnfcimfgdmchchmmg" ascii wide
        $ext_778 = "mciddpldhpdpibckghnaoidpolnmighk" ascii wide
        $ext_779 = "mjbimaghobnkobfefccnnnjedoefbafl" ascii wide
        $ext_780 = "mnbhnjecaofgddbldmppbbdlokappkgk" ascii wide
        $ext_781 = "nicmhgecboifljcnbbjlajbpagmhcclp" ascii wide
        $ext_782 = "njhfmnfcoffkdjbgpannpgifnbgdihkl" ascii wide
        $ext_783 = "noilkpnilphojpjaimfcnldblelgllaa" ascii wide
        $ext_784 = "obcfoaeoidokjbaokikamaljjlpebofe" ascii wide
        $ext_785 = "oejafikjmfmejaafjjkoeejjpdfkdkpc" ascii wide
        $ext_786 = "ogaclpidpghafcnbchgpbigfegdbdikj" ascii wide
        $ext_787 = "opmelhjohnmenjibglddlpmbpbocohck" ascii wide
        $ext_788 = "pbilbjpkfbfbackdcejdmhdfgeldakkn" ascii wide
        $ext_789 = "pcmdfnnipgpilomfclbnjpbdnmbcgjaf" ascii wide
        $ext_790 = "pedokobimilhjemibclahcelgedmkgei" ascii wide
        $ext_791 = "plnlhldekkpgnngfdbdhocnjfplgnekg" ascii wide
        $ext_792 = "nonjdcjchghhkdoolnlbekcfllmednbl" ascii wide
        $ext_793 = "pgeolalilifpodheeocdmbhehgnkkbak" ascii wide
        $ext_794 = "gnamdgilanlgeeljfnckhboobddoahbl" ascii wide
        $ext_795 = "alecjlhgldihcjjcffgjalappiifdhae" ascii wide
        $ext_796 = "kelbkhobcfhdcfhohdkjnaimmicmhcbo" ascii wide
        $ext_797 = "dpglnfbihebejclmfmdcbgjembbfjneo" ascii wide
        $ext_798 = "lpjhpdcflkecpciaehfbpafflkeomcnb" ascii wide
        $ext_799 = "ckkgmccefffnbbalkmbbgebbojjogffn" ascii wide
        $ext_800 = "ppmibgfeefcglejjlpeihfdimbkfbbnm" ascii wide
        $ext_801 = "ginfoagmgomhccdaclfbbbhfjgmphkph" ascii wide
        $ext_802 = "mpneoicaochhlckfkackiigepakdgapj" ascii wide
        $ext_803 = "djffibmpaakodnbmcdemmmjmeolcmbae" ascii wide
        $ext_804 = "pejkmgfabkeddfcfldloonjbikjddapb" ascii wide
        $ext_805 = "gmddfjhfjgbmabkihepijkanhmlooajl" ascii wide
        $ext_806 = "kajjcgpohlkdcjfkcbkkbhapafcblaom" ascii wide
        $ext_807 = "anbnajjakpmfdofijejenaclbceejlll" ascii wide
        $ext_808 = "jkkmcoihchcflfjnigngdegbemipdlnl" ascii wide
        $ext_809 = "ajmchakbijebimbgcohecngliijaddin" ascii wide
        $ext_810 = "edpoobbacbcmfpnfpjoambjbihhobooi" ascii wide
        $ext_811 = "opfogdennafhaoihhkocppaajlkpbfbn" ascii wide
        $ext_812 = "ikojddbdekpboemgplhbloojlncbpmdd" ascii wide
        $ext_813 = "chlpbdodahbpifpjbcoocpfadoffdbpb" ascii wide
        $ext_814 = "flbcjbhgomclbhlchggbmnpekhfeacim" ascii wide
        $ext_815 = "aadmpgppfacognoeobmheghfiibdplcf" ascii wide
        $ext_816 = "abgfholnofpihncfdmombecmohpkojdb" ascii wide
        $ext_817 = "aciloeifdphkogbpagikkpiecbjkmedn" ascii wide
        $ext_818 = "acmgemnaochmalgkipbamjddcplkdmjm" ascii wide
        $ext_819 = "addpbbembilhmnkjpenjgcgmihlcofja" ascii wide
        $ext_820 = "adfjcmhegakkhojnallobfjbhenbkopj" ascii wide
        $ext_821 = "aeklcpmgaadjpglhjmcidlekijpnmdhc" ascii wide
        $ext_822 = "afifalglopajkmdkgnphpfkmgpgdngfj" ascii wide
        $ext_823 = "agldjlpmeladgadoikdbndmeljpmnajl" ascii wide
        $ext_824 = "ahmmgfhcokekfofjdndgmkffifklogbo" ascii wide
        $ext_825 = "aippaajbmefpjeajhgaahmicdpgepnnm" ascii wide
        $ext_826 = "akdpobnbjepjbnjklkkbdafemhnbfldj" ascii wide
        $ext_827 = "akhiflcfcbnheaofcaflofbmnkmjlnno" ascii wide
        $ext_828 = "aklklkifmplgnobmieahildcfbleamdb" ascii wide
        $ext_829 = "alppaffmlaefpmopolgpkgmncopkbbep" ascii wide
        $ext_830 = "amdnpfcpjglkdfcigaccfgmlmdepdpeo" ascii wide
        $ext_831 = "aomepndmhbbklcjcknnhdabaaofahjcj" ascii wide
        $ext_832 = "badbchbijjjadlpjkkhmefaghggjjeha" ascii wide
        $ext_833 = "bbbdfjdplonnggfjjbjhggobffkggnkm" ascii wide
        $ext_834 = "bbdldenhkjcoikalkfkgolomdpnncofc" ascii wide
        $ext_835 = "bcdjcbgogdomoebdcbniaifnacjbglil" ascii wide
        $ext_836 = "bcepmajicjlaoleoljbpaemkfghohmib" ascii wide
        $ext_837 = "bdbablmeheiahecklheciomhmkplcoml" ascii wide
        $ext_838 = "bfeecodfffgkdedfhmgbfindokikafid" ascii wide
        $ext_839 = "bhifimmocncplbnikchffepggmofkake" ascii wide
        $ext_840 = "blipiofdiknkllpajgepiiigfmfgnfep" ascii wide
        $ext_841 = "bmagbmnmkaknlnoohbmobfmlgndijecb" ascii wide
        $ext_842 = "bnecbeikepeloplclngelcgmgdnafhlp" ascii wide
        $ext_843 = "bpnmalopmgpilaoikaeafokedkkonhea" ascii wide
        $ext_844 = "cbncogjaakomibjcgdkpdjmlhfcjfojc" ascii wide
        $ext_845 = "ccgmdfdcnpcfmpceggggmnhbolkhlffi" ascii wide
        $ext_846 = "ccmnnlcciddhkdllgfmkojmmmpahdhlp" ascii wide
        $ext_847 = "cdpmhflbdaoifgkmlhpfkbfgcifchgpn" ascii wide
        $ext_848 = "cepgcjakdboolfkcbihdokfjjkeaddin" ascii wide
        $ext_849 = "cfadfngejcdogjkkdohpkgeodjooogip" ascii wide
        $ext_850 = "cgdmknakejoaompdmdeddpgmjffnniab" ascii wide
        $ext_851 = "cgodgjmdljiecnbcgdampafcmlgmfmid" ascii wide
        $ext_852 = "cibigjhoekijbagpgcgpgimebaiocdgm" ascii wide
        $ext_853 = "cjbdbomgdbdgdlainhobpjnfkoidcond" ascii wide
        $ext_854 = "clndgmolhlkchkbiinamamnbibkakiml" ascii wide
        $ext_855 = "cmbfgkkjfkmmhalhebnhmanbenfghkcm" ascii wide
        $ext_856 = "cncepimkmnhgbjmbcgoomegdkdhplihm" ascii wide
        $ext_857 = "cnfbbaddndiehkmhdmmngecaofaojaeo" ascii wide
        $ext_858 = "codilkcdacpeklilmgjknekfpminaieo" ascii wide
        $ext_859 = "dakenmmdlklnjdpdfmdjccpeapmijaad" ascii wide
        $ext_860 = "dapecdhpbakbfcoijjpdfoffnajhifej" ascii wide
        $ext_861 = "dckadbanpeemhkphnnllamgolhbbbebi" ascii wide
        $ext_862 = "ddodaoihhhohncjalnjgmgnlfhgckgdj" ascii wide
        $ext_863 = "dhbhgfiodedkhgocailljbhcfjhplibb" ascii wide
        $ext_864 = "dhcnonhheahlocjbbpkbammanpenpfop" ascii wide
        $ext_865 = "dhgmdjkeagnhamkedcejighocjkkijli" ascii wide
        $ext_866 = "dinlhhblgeikohhbfkcoeggglbjlanhg" ascii wide
        $ext_867 = "djjdjlbigcdjlghdioabbkjhdelmdhai" ascii wide
        $ext_868 = "dkcppkdodfegjkeefohjancleioblabi" ascii wide
        $ext_869 = "dkfbfgncahnfghoemhmmlfefhpolihom" ascii wide
        $ext_870 = "dmklpmfpkokephcjdmocddkhilglgajl" ascii wide
        $ext_871 = "dnimnhhaiphlclcocakkfgnnekoggjpl" ascii wide
        $ext_872 = "doecpeonnonddhfpabfgblijljennlcj" ascii wide
        $ext_873 = "dofbgmolpdoknlknfjddecnahgjpinpb" ascii wide
        $ext_874 = "dppogkehbpnikehcmadgkbimjnmhdnlo" ascii wide
        $ext_875 = "eapceolnilleaiiaapgionibccekkeom" ascii wide
        $ext_876 = "ecaejcfpngljeinjmahknbemhnddiioe" ascii wide
        $ext_877 = "ecgafllkghmmbnhacnpcobibalonhkkj" ascii wide
        $ext_878 = "edfmeionipdoohiagoaefljjhififgnl" ascii wide
        $ext_879 = "edgbooeklapanaclbchdiaekalebmfgb" ascii wide
        $ext_880 = "edohegfjelahakooigmnmkmjofcjgofe" ascii wide
        $ext_881 = "eeeiekjkpbneogggaajnjldadjmclhlo" ascii wide
        $ext_882 = "eejkpejdfojkbklnlnpgpojoidojbhnh" ascii wide
        $ext_883 = "efckalhlcogbdbfopffmbacghfoelaia" ascii wide
        $ext_884 = "efnaoofiidefjeefpnheopknaciohldg" ascii wide
        $ext_885 = "egdpmjnldpefdaiekiapjkanabfiaodp" ascii wide
        $ext_886 = "egicjjdcjhfdnejimnhngogjmoajffpm" ascii wide
        $ext_887 = "ejcefeinlmdmpnohebfckmodhdkhlgmk" ascii wide
        $ext_888 = "ejighbgeedkpcambhfkohdalcgckdein" ascii wide
        $ext_889 = "empoeejllbcgpkmghimibnapemegnihf" ascii wide
        $ext_890 = "enlaekiichndcbohopenblignipkjaoa" ascii wide
        $ext_891 = "enmomapaolnpbaenhilkjhmobpggjcpm" ascii wide
        $ext_892 = "eohabjkmhajbeaejogdikpgapkeigdki" ascii wide
        $ext_893 = "eoijplcnfnjgofchhdkkhpfcjkcefgkb" ascii wide
        $ext_894 = "facihnceaoboeoembnbmdlecmkpioacc" ascii wide
        $ext_895 = "fagaafjhdmoagacggplmbpganjfjjpcf" ascii wide
        $ext_896 = "fanonokndfeibplocpeipgfbopkigcce" ascii wide
        $ext_897 = "faokbgedcfhnfecloigcihpplicdnann" ascii wide
        $ext_898 = "fcdopghpidfdeglcheccmehiaedgpmkm" ascii wide
        $ext_899 = "fdacngbbemokpkmdkdefkoodndakgejc" ascii wide
        $ext_900 = "fdfffeipjpofnkmdkadjcjohdfoeblhk" ascii wide
        $ext_901 = "ffhamkjhfajcjlnobkogimnhiagohgfg" ascii wide
        $ext_902 = "fjnbjacfigdidgeeommhbdhnojamhpfg" ascii wide
        $ext_903 = "fjohhelccbogecmolmjemopgackpnmpg" ascii wide
        $ext_904 = "flagaiaajbikpfnnkodcphdcmgefmbcl" ascii wide
        $ext_905 = "flgfngbiaanimkhjkojnmilfalidpign" ascii wide
        $ext_906 = "fmngfipkcebejdconcibohjjgfmokhpa" ascii wide
        $ext_907 = "fnblapfcdifokdbkpcbhpkajlkgmcjii" ascii wide
        $ext_908 = "fpdjcfokkeooncckcolkmmppebjnfhgh" ascii wide
        $ext_909 = "fphafkamioonlcelldogidajbcmmicco" ascii wide
        $ext_910 = "fpjbgjpkfcanmdgjpmnnmoekkaahmafg" ascii wide
        $ext_911 = "fplmpcijomgjmfbjcidbgpjdmhmamlkf" ascii wide
        $ext_912 = "gdacidkmmbdpkedejaljplnfhjidomio" ascii wide
        $ext_913 = "gdoomgeeelkgcmmoibloelbodkpggdle" ascii wide
        $ext_914 = "geoolholooeeblajdjffdmknpecbkmah" ascii wide
        $ext_915 = "ghfgeefhkkoajgmnopaldgcagohakhmg" ascii wide
        $ext_916 = "ghhanhhegklhcoffmgkdbiekfhmbfbnc" ascii wide
        $ext_917 = "gjkigcdoljdojaaomnadffdhggoobdpc" ascii wide
        $ext_918 = "gkjkhpbembbjogoiejpkehohclfoljbp" ascii wide
        $ext_919 = "glibnbcgclecomknccifdaglefljfoej" ascii wide
        $ext_920 = "gllogphgdmclhfledlcgmdolngohamcl" ascii wide
        $ext_921 = "haagbldencigkgikfekmoaaofambnafp" ascii wide
        $ext_922 = "haglbigaalkckkedjamjibfnklbbodck" ascii wide
        $ext_923 = "hcgepcgbgnleafnfcepjbekchbdmekfa" ascii wide
        $ext_924 = "hdbchphkjjidcfidaelcpmonodhhaahp" ascii wide
        $ext_925 = "hdljgflalglmllbagpacjmkdiggliidk" ascii wide
        $ext_926 = "hdpnlijiblkmokbjljbahhgkpokgpkli" ascii wide
        $ext_927 = "heaphjoejcpdagahbnkkloiaicpadomp" ascii wide
        $ext_928 = "hjfmdhbmpagpfheceengkakdmpncmlif" ascii wide
        $ext_929 = "hjkjkmkoklbhjhlddialffkchddlncjb" ascii wide
        $ext_930 = "hjoihkjijjbkiglgeghbokincmidfped" ascii wide
        $ext_931 = "hncokbmdmbmmlkjhoagcpokehopdikhc" ascii wide
        $ext_932 = "hnhpnbajfmmopedidmiablkcdnlegkmd" ascii wide
        $ext_933 = "homdfmaeflodjknffbnhagmlhmgmbjac" ascii wide
        $ext_934 = "iccagibmclklcmiejfddepgffgkhnnib" ascii wide
        $ext_935 = "idkllmolbaiailjfidkjcidapkddidbg" ascii wide
        $ext_936 = "ifbffcgakkboaffkidggpcjolehhhbfd" ascii wide
        $ext_937 = "ifdebecchhapkfdbcbhpmjonmbpfpnck" ascii wide
        $ext_938 = "igbcfkjflkgamnoikcpiljglnmjnkjac" ascii wide
        $ext_939 = "iiblgogamkmdfojoclpdhainbndfpcci" ascii wide
        $ext_940 = "inkankpmoblmficechfgfinajifbfkdn" ascii wide
        $ext_941 = "ioejcipbmdjinhfciojiacdjolkabkmn" ascii wide
        $ext_942 = "iojhbljpppeociniiemjfelmdcgikmep" ascii wide
        $ext_943 = "ipgnnndhgeaclopjgiihppbbfnmkmjcm" ascii wide
        $ext_944 = "jckaglinbbflgcklfgacjdmgpnccmdng" ascii wide
        $ext_945 = "jfocahgaekfaemhfcfefcodphgpinnch" ascii wide
        $ext_946 = "jgbkgjepkeklblmlhnpjmnbinmifjenc" ascii wide
        $ext_947 = "jlbebokeclkofhchdepbojfhmocdlhfl" ascii wide
        $ext_948 = "jlbhkoohfmnikpalgglhpadlbeiobkaa" ascii wide
        $ext_949 = "jmlbnlcodmikhdpbjjdemgaebjgmpooa" ascii wide
        $ext_950 = "jnmckphflgdpioinbjaeckdajkbgcfgg" ascii wide
        $ext_951 = "kcjahchbheejjpdpohgfkaoknhcdjjnh" ascii wide
        $ext_952 = "kdihodbgfndblemlklkllhfjhiidbgih" ascii wide
        $ext_953 = "kefmhdhaebhmdeaabcgoaegmgodncebc" ascii wide
        $ext_954 = "kicmnilchjfefpceoaiopdpbpkicgjjm" ascii wide
        $ext_955 = "kigiheamdfmilbhkfdploghfnndcgkko" ascii wide
        $ext_956 = "kjgceeikbnmddoaggelkkpljdabhghkc" ascii wide
        $ext_957 = "kkeojhapoadcdlmkjlakdbhfkldbbmgi" ascii wide
        $ext_958 = "klblfmpeelmpnadjahhdakiomhaepogb" ascii wide
        $ext_959 = "kmfiklhdkhidbmofjbgmpeaogglkndpe" ascii wide
        $ext_960 = "knacgnmpceaffedmgegknkfcnejjhdpp" ascii wide
        $ext_961 = "kppjffaccdlhfeleafnohmfkgimdjmgg" ascii wide
        $ext_962 = "lbbegfjhlhpikmhbdcfcoadegdldmaen" ascii wide
        $ext_963 = "lbjgbekokephmmfllmpglefmoaihklpn" ascii wide
        $ext_964 = "lblnngjkgcpplmddebmefokmccpflhip" ascii wide
        $ext_965 = "lcdabcbanafchdlcbdjgngcplnkijala" ascii wide
        $ext_966 = "lcgjhoonomcmjpbnijfohbdhhjmhjlal" ascii wide
        $ext_967 = "ldkienofjncecbbnmhpngiiidekfcdoe" ascii wide
        $ext_968 = "lemhpidjofhodofghkakoglahdafpcbe" ascii wide
        $ext_969 = "lgekbdjboenacbkiabfkkcpjgacmjcdg" ascii wide
        $ext_970 = "lggmpibegkcnfogpophgnchognofcdgo" ascii wide
        $ext_971 = "ljppknljdefmnkckkdjaokhlncbiehgo" ascii wide
        $ext_972 = "lkdahidfbdadmblpkopllegopldfbhge" ascii wide
        $ext_973 = "llngndcpphncgeledehpklbeheadnoan" ascii wide
        $ext_974 = "lmmdoemglmnjenhfcjkhgpkgiedcejmn" ascii wide
        $ext_975 = "lniooknjghghdjoehegcoinmbhdbhcck" ascii wide
        $ext_976 = "makliapgjjpdkkaikobcmdhkfbfcoafk" ascii wide
        $ext_977 = "maohnjppabopdhfkholcdkpehdojnpoc" ascii wide
        $ext_978 = "mcadalidfbmnponoamfdjlahdeheommb" ascii wide
        $ext_979 = "mcafdholbcjhepgnpfdogaiagjmlfcon" ascii wide
        $ext_980 = "meioomnaphfjchjidcfnbadkbaaoanok" ascii wide
        $ext_981 = "mjbmelinkhpkmbjnocdklkjpiilpikba" ascii wide
        $ext_982 = "mkghdamdheccacmkmnchkaoljoflpoek" ascii wide
        $ext_983 = "mkjcnnfcmmniieaidfadidepdgfppfdj" ascii wide
        $ext_984 = "mmhaojkmpbmgbkojlagnhmjlfmnaglla" ascii wide
        $ext_985 = "mmlhchoolkdnmnddgmoohigffekjnofo" ascii wide
        $ext_986 = "mmmapklofkmbcahafjmiogdbmpagimlp" ascii wide
        $ext_987 = "mngcfgonjbdbdbifcbhmdiddloganbcc" ascii wide
        $ext_988 = "mnnpffgmgkbdllleeihdgfgleomdhacm" ascii wide
        $ext_989 = "moalaminambcgbljenplldelnhnaikke" ascii wide
        $ext_990 = "moljhdcbomchgdffhddpicbokacnbjoj" ascii wide
        $ext_991 = "mpdpjfobafahmgicjmpnfklbphhlacel" ascii wide
        $ext_992 = "mpfleoaldoclbjhfkgbmnelkkbolbegl" ascii wide
        $ext_993 = "nafbodmhgaabbfchodpkmpnibgjmeeei" ascii wide
        $ext_994 = "naofchadlleomaipaienfedidkiodamo" ascii wide
        $ext_995 = "nbbeiofjfjmnicfhkfbjdggbclmbaioc" ascii wide
        $ext_996 = "nbblafbmmogmlhejjondcclcgbkdmjln" ascii wide
        $ext_997 = "nbekcbebginchflfegofcjjmojpppnad" ascii wide
        $ext_998 = "nbhjdcacphemibgeamjkmeknfeffgngk" ascii wide
        $ext_999 = "nchffcpkbehklpbdodlakgdbnkdcnpbi" ascii wide
        $ext_1000 = "nckldhnoondmiheikhblobkgcfchcbld" ascii wide
        $ext_1001 = "ncnonnloajjbpdpgnelmlbflmbhlilid" ascii wide
        $ext_1002 = "ncpjlhellnlcjnjmablbaingipdemidh" ascii wide
        $ext_1003 = "ndchgkeilnpiefnoagcbnlellpcfmjic" ascii wide
        $ext_1004 = "ndeejbgcbhehjpjmngniokeleedmjmap" ascii wide
        $ext_1005 = "ndihciopmidkbamcfgpdmojcpalolfgo" ascii wide
        $ext_1006 = "neafafemicnbclhpojeoiemihogeejhl" ascii wide
        $ext_1007 = "nekimocmhfdimckbgchifahcgafhnagb" ascii wide
        $ext_1008 = "nenaiblmmandfgaiifppcegejpinkebl" ascii wide
        $ext_1009 = "neplbnhjlkmpekfcjibdidioejnhejfl" ascii wide
        $ext_1010 = "nepnhilmahdmejhghfbjhhabaioioeel" ascii wide
        $ext_1011 = "nfanjklinojeimbhmfliomdihldjhfpm" ascii wide
        $ext_1012 = "nfebelgoldoapjgfkekcmbddpljakakp" ascii wide
        $ext_1013 = "nfhbpopnbgigkljgmelpfncnghjpdopf" ascii wide
        $ext_1014 = "nfpnclghflfcgkgdjcbpoljlafndbomk" ascii wide
        $ext_1015 = "ngaccohdjpkgnghichikgcpfagnoeeim" ascii wide
        $ext_1016 = "ngajighkghnbfnleddljedblnjaggebo" ascii wide
        $ext_1017 = "ngchnhjdpgpkapghgpncmommhelegfbh" ascii wide
        $ext_1018 = "ngeofnobniohmdmdkliflkeppfgbjpgn" ascii wide
        $ext_1019 = "nglggaejaflihehbajhppedepephbfae" ascii wide
        $ext_1020 = "nhnemamgicdjigoedllaicngcfihkmhf" ascii wide
        $ext_1021 = "nhneoegahiihkkgdindfdnobhhhlpfnm" ascii wide
        $ext_1022 = "njablodeioakdgahodegclphmnbaphin" ascii wide
        $ext_1023 = "njdegihoinoiplfpbcckmjahlnpeipii" ascii wide
        $ext_1024 = "njliieipbkencklladfemkkipmfcjiom" ascii wide
        $ext_1025 = "nklckhbegicdajpehmmpbnpelkdjmdoc" ascii wide
        $ext_1026 = "nkopnpaipcceikcmfcjlacgkjoglodag" ascii wide
        $ext_1027 = "nldffbaphciaaophmdnikgkengbmigli" ascii wide
        $ext_1028 = "nmkfcjaghjoedelgkomoifnpdejjpcbj" ascii wide
        $ext_1029 = "nmlmdkblidkckbhidgfgghajlkgjijkp" ascii wide
        $ext_1030 = "nnceiipjfkdobpenbmnajbkdfiklajgl" ascii wide
        $ext_1031 = "noiinnecebffnjggilfhailhhgdilbld" ascii wide
        $ext_1032 = "nojmjafalbmmoohpmjphalepmfnmhfao" ascii wide
        $ext_1033 = "npcndkopgafkjggoledlgfblodppnckj" ascii wide
        $ext_1034 = "nphiadicgehlpbniemnkhinphngoeaeg" ascii wide
        $ext_1035 = "oaihijkoodmmaibfhojdinffpinmhdji" ascii wide
        $ext_1036 = "oanlnaeipdakcmafockfiekhdklfidjb" ascii wide
        $ext_1037 = "oanplobhgngkpkpeihcdojkongpiheci" ascii wide
        $ext_1038 = "obahibdkmhmnenkcdpakilchcppihopl" ascii wide
        $ext_1039 = "obgdpcjbebcaphmigjhogcikejnlbjgl" ascii wide
        $ext_1040 = "ocfpmgbbkjeblbhdehminjdjffhcidbi" ascii wide
        $ext_1041 = "ocgfhclcahimdhfjgmakmfdnhomofljo" ascii wide
        $ext_1042 = "ocponkhpfikgnggeflddgkfcmhjejedo" ascii wide
        $ext_1043 = "odoenahafpbigcelejhbkkhnjfleanok" ascii wide
        $ext_1044 = "oehamnhnpejphgpkgnenefolepinadjj" ascii wide
        $ext_1045 = "oejbnchocabaoicconfnbjghebmbfemc" ascii wide
        $ext_1046 = "oejmcobpfiiladgbfpknibppfnekbolo" ascii wide
        $ext_1047 = "oemkcngaaomgokaclafmkcgcpbfelmnb" ascii wide
        $ext_1048 = "ofbfieekadnmifbaoigkcffobkkjblep" ascii wide
        $ext_1049 = "ofgihclaiecmjbfjnajjimdbjnbiimkk" ascii wide
        $ext_1050 = "ofkjndegefemablfmefngnpchlhapdmi" ascii wide
        $ext_1051 = "ofockibbbgfclddbpbhhohdldgkomhgm" ascii wide
        $ext_1052 = "ogegpnamjdpcadpldhijjlhkicgbnkjj" ascii wide
        $ext_1053 = "ogiaghccmoklogdlbchapejmjnnlichn" ascii wide
        $ext_1054 = "ohjoklkmollkbcibgddolpmpgaoophfl" ascii wide
        $ext_1055 = "ohobkendnpiijpeiaimjbannfcmhaogi" ascii wide
        $ext_1056 = "ohoingjkmkkoffkdmbpipdncbkhaaefd" ascii wide
        $ext_1057 = "oihecidjnjpjfeefkambkjgebbmpahgn" ascii wide
        $ext_1058 = "oilikkahlcnchaipbojfgejapechblbl" ascii wide
        $ext_1059 = "ojfjgkolegfhneacbgcjaoajfgcfoapf" ascii wide
        $ext_1060 = "ojhlagjgjbjfgllocdhlpnkbdlcipnmo" ascii wide
        $ext_1061 = "ojmpgbcmiimbkmjfgmcneplkneleehcc" ascii wide
        $ext_1062 = "ojnlggfhmoioajgmnelfdpjojaeknjog" ascii wide
        $ext_1063 = "okgnpdnekilbcgcfeheanbpbhnhmopfc" ascii wide
        $ext_1064 = "okjdiicjoeloipmgdopdmhpebnnfadih" ascii wide
        $ext_1065 = "okphhehkikoonipdjmhglcmlgccjcblp" ascii wide
        $ext_1066 = "olochidfgadpdbdmdfbhgimiffnllaij" ascii wide
        $ext_1067 = "ombenndgcnmcnfohnbbjcmbmfmpefojc" ascii wide
        $ext_1068 = "omclahaofiigfggelbcleagcphjhabmp" ascii wide
        $ext_1069 = "onjjlcdmafgcjdbhmlnpmheobbfeilah" ascii wide
        $ext_1070 = "onnmfhejbikffoenamcfglpjnmmbkdeg" ascii wide
        $ext_1071 = "oonheecobachpkogdjjnemiipogpgnmg" ascii wide
        $ext_1072 = "opbobdfddmiemhekjiglckcenhpfdbjm" ascii wide
        $ext_1073 = "opjpfngjbdmgkilopbnapbkbngedcpmj" ascii wide
        $ext_1074 = "oplhjpchbbngmpgcpjcbijhfehbhodgi" ascii wide
        $ext_1075 = "oppbpkjmehgijcpeddkpbadoidfpcblg" ascii wide
        $ext_1076 = "paddichbcfehpelokpidnagccddbpkin" ascii wide
        $ext_1077 = "pajbempmgmalnfpbnpclkelnhfccikal" ascii wide
        $ext_1078 = "pboddlnfegdnifbhepjegnokocjpadpd" ascii wide
        $ext_1079 = "pcbpmbmpjjibcmodpaomahiokikjomgc" ascii wide
        $ext_1080 = "pcembleiffdccjkcebaodmhgkopipdan" ascii wide
        $ext_1081 = "pcgcmplcfdfkkkmaggghdghnlddkpbbo" ascii wide
        $ext_1082 = "pdhibfagbndnidgfjkhdhlfibdoofbji" ascii wide
        $ext_1083 = "pdloaiifhmlbhhppajjmfpijopfeenoo" ascii wide
        $ext_1084 = "pehnljkefahmlhifockljagcfcpljclc" ascii wide
        $ext_1085 = "pelnnoacfeaanpmnmacjjnnpgfggekig" ascii wide
        $ext_1086 = "pfekelemlpmelhipncgddloaflehglmb" ascii wide
        $ext_1087 = "pfepcffcdodcancalckiencamnonoebl" ascii wide
        $ext_1088 = "pfpgpbfndacjjjdlgefggndhionakfmb" ascii wide
        $ext_1089 = "pghkmhmjldklacabcgkaaboikfaaogmi" ascii wide
        $ext_1090 = "pgilbgknfcnjjblfnjojmcpkggipblci" ascii wide
        $ext_1091 = "pgleokbigapafgjodffamlhdkhiagdgb" ascii wide
        $ext_1092 = "phkafpikdokjpogdhjpkcgfjpfgnlgeo" ascii wide
        $ext_1093 = "phmogllmicehmpglfobbihoelfidjnpd" ascii wide
        $ext_1094 = "pihogmfmhefemijkgmbimkngninbkkce" ascii wide
        $ext_1095 = "pilmbpeapchjcnldfomimmcfoigoenoc" ascii wide
        $ext_1096 = "pinfndnjmdocmimbeonilpahdaldopjc" ascii wide
        $ext_1097 = "pinkcaefpkjpljfflabpkcgbkpbomdfk" ascii wide
        $ext_1098 = "pjabdohmcokffcednbgpeoifpdbfgfbj" ascii wide
        $ext_1099 = "pjjmcpmjocebmjmhdclbiheoideefiad" ascii wide
        $ext_1100 = "plcdglhlbmlnfoghfhmbhehapfadedod" ascii wide
        $ext_1101 = "pmdakkjbaeioodmomlmnklahihodjcjk" ascii wide
        $ext_1102 = "pmnpldnflfopbhndkjndecojdpgecckf" ascii wide
        $ext_1103 = "pnamonkagicmlnalnlcdaoeenhlgdklf" ascii wide
        $ext_1104 = "poeokidblnamjkagggonidcigafaobki" ascii wide
        $ext_1105 = "pofffhlknjbjolmfoeagdmbbdbjjmeki" ascii wide
        $ext_1106 = "polgnkadhhhmlahkhhbicledbpklnake" ascii wide
        $ext_1107 = "ppicajcmopaimnnikbafgknffbdmomfk" ascii wide
        $ext_1108 = "ppmbiomgjfenipmnjiiaemcaboaeljil" ascii wide
        $ext_1109 = "bmngkajcejghcgafbobemkpjboikmgfi" ascii wide
        $ext_1110 = "deciloopcooglpjhomblbbjeeenohbpg" ascii wide
        $ext_1111 = "gabbbocakeomblphkmmnoamkioajlkfo" ascii wide
        $ext_1112 = "ggolfgbegefeeoocgjbmkembbncoadlb" ascii wide
        $ext_1113 = "mdpgppkombninhkfhaggckdmencplhmg" ascii wide
        $ext_1114 = "fgaapohcdolaiaijobecfleiohcfhdfb" ascii wide
        $ext_1115 = "iibnodnghffmdcebaglfgnfkgemcbchf" ascii wide
        $ext_1116 = "olkpikmlhoaojbbmmpejnimiglejmboe" ascii wide
        $ext_1117 = "bhfoemlllidnfefgkeaeocnageepbael" ascii wide
        $ext_1118 = "nilbfjdbacfdodpbdondbbkmoigehodg" ascii wide
        $ext_1119 = "eikbfklcjampfnmclhjeifbmfkpkfpbn" ascii wide
        $ext_1120 = "pfnmibjifkhhblmdmaocfohebdpfppkf" ascii wide
        $ext_1121 = "cgpbghdbejagejmciefmekcklikpoeel" ascii wide
        $ext_1122 = "klejifgmmnkgejbhgmpgajemhlnijlib" ascii wide
        $ext_1123 = "ceoldlgkhdbnnmojajjgfapagjccblib" ascii wide
        $ext_1124 = "mnafnfdagggclnaggnjajohakfbppaih" ascii wide
        $ext_1125 = "oknpgmaeedlbdichgaghebhiknmghffa" ascii wide
        $ext_1126 = "pcaaejaejpolbbchlmbdjfiggojefllp" ascii wide
        $ext_1127 = "lmcajpniijhhhpcnhleibgiehhicjlnk" ascii wide
        $ext_1128 = "lnocaphbapmclliacmbbggnfnjojbjgf" ascii wide
        $ext_1129 = "bhcpgfhiobcpokfpdahijhnipenkplji" ascii wide
        $ext_1130 = "dambkkeeabmnhelekdekfmabnckghdih" ascii wide
        $ext_1131 = "dgjmdlifhbljhmgkjbojeejmeeplapej" ascii wide
        $ext_1132 = "emechknidkghbpiodihlodkhnljplpjm" ascii wide
        $ext_1133 = "hajlccgbgjdcjaommiffaphjdndpjcio" ascii wide
        $ext_1134 = "dljdbmkffjijepjnkonndbdiakjfdcic" ascii wide
        $ext_1135 = "cjmpdadldchjmljhkigoeejegmghaabp" ascii wide
        $ext_1136 = "jlkfgpiicpnlbmmmpkpdjkkdolgomhmb" ascii wide
        $ext_1137 = "njdkgjbjmdceaibhngelkkloceihelle" ascii wide
        $ext_1138 = "phoehhafolaebdpimmbmlofmeibdkckp" ascii wide
        $ext_1139 = "pccfaccnfkjmdlkollpiaialndbieibj" ascii wide
        $ext_1140 = "fbhbpnjkpcdmcgcpfilooccjgemlkinn" ascii wide
        $ext_1141 = "dppilebghcniomddkpphiminideiajff" ascii wide
        $ext_1142 = "ojmbbkdflpfjdceflikpkbbmmbfagglg" ascii wide
        $ext_1143 = "chmaijbnjdnkjknoigffoohjhpejjppd" ascii wide
        $ext_1144 = "jhcfnojahmdghhebdaoijngclknfkbjn" ascii wide
        $ext_1145 = "akdbogfpgohikflhccclloneidjkogog" ascii wide
        $ext_1146 = "lgjogljbnbfjcaigalbhiagkboajmkkj" ascii wide
        $ext_1147 = "aemaecahdckfllfldhgimjhdgiaahean" ascii wide
        $ext_1148 = "klbibkeccnjlkjkiokjodocebajanakg" ascii wide
        $ext_1149 = "fmfjhicbjecfchfmpelfnifijeigelme" ascii wide
        $ext_1150 = "acdfdofofabmipgcolilkfhnpoclgpdd" ascii wide
        $ext_1151 = "oobppndjaabcidladjeehddkgkccfcpn" ascii wide
        $ext_1152 = "aonedlchkbicmhepimiahfalheedjgbh" ascii wide
        $ext_1153 = "aoeacblfmdamdejeiaepojbhohhkmkjh" ascii wide
        $ext_1154 = "eoeoincjhpflnpdaiemgbboknhkblome" ascii wide
        $ext_1155 = "onbkopaoemachfglhlpomhbpofepfpom" ascii wide
        $ext_1156 = "inlgdellfblpplcogjfedlhjnpgafnia" ascii wide
        $ext_1157 = "ejfajpmpabphhkcacijnhggimhelopfg" ascii wide
        $ext_1158 = "pgjndpcilbcanlnhhjmhjalilcmoicjc" ascii wide
        $ext_1159 = "napifgkjbjeodgmfjmgncljmnmdefpbf" ascii wide
        $ext_1160 = "glgemekgfjppocilabhlcbngobillcgf" ascii wide
        $ext_1161 = "klmjcelobglnhnbfpmlbgnoeippfhhil" ascii wide
        $ext_1162 = "ldbfffpdfgghehkkckifnjhoncdgjkib" ascii wide
        $ext_1163 = "mbacbcfdfaapbcnlnbmciiaakomhkbkb" ascii wide
        $ext_1164 = "mdnmhbnbebabimcjggckeoibchhckemm" ascii wide
        $ext_1165 = "lfedlgnabjompjngkpddclhgcmeklana" ascii wide
        $ext_1166 = "mdpljndcmbeikfnlflcggaipgnhiedbl" ascii wide
        $ext_1167 = "npdpplbicnmpoigidfdjadamgfkilaak" ascii wide
        $ext_1168 = "ibehiiilehaakkhkigckfjfknboalpbe" ascii wide
        $ext_1169 = "lalpacfpfnobgdkbbpggecolckiffhoi" ascii wide
        $ext_1170 = "hdbipekpdpggjaipompnomhccfemaljm" ascii wide
        $ext_1171 = "gfjocjagfinihkkaahliainflifnlnfc" ascii wide
        $ext_1172 = "ickfamnaffmfjgecbbnhecdnmjknblic" ascii wide
        $ext_1173 = "bmcnncbmipphlkdmgfbipbanmmfdamkd" ascii wide
        $ext_1174 = "miejmllodobdobgjbeonandkjhnhpjbn" ascii wide
        $ext_1175 = "mabdjppmcjpjploliggpbonahnjjlgkf" ascii wide

    condition:
        any of ($ext_*)
}

rule ExtSentry_compromised_BrowserExtensions
{
    meta:
        description = "Detects browser extension IDs categorized as compromised by ExtSentry"
        author = "ExtSentry / mthcht"
        date = "2026-03-27"
        reference = "https://github.com/mthcht/awesome-lists"
        category = "compromised"
        tlp = "WHITE"

    strings:
        $ext_0 = "odccobbfnngplckpongkahajfjpnbcck" ascii wide
        $ext_1 = "afefmfbcccnppcaiebpmbpmddhilkkdi" ascii wide
        $ext_2 = "oaljkhbgbedmfoiieocoenglpaeogjmf" ascii wide
        $ext_3 = "ndajnaaobjaganokllcgbapngenfbgkc" ascii wide
        $ext_4 = "okjdbeegldeilceaflghgfdemobmfhbd" ascii wide
        $ext_5 = "jhigofkbdbndeooldpdhmphldaglejlh" ascii wide
        $ext_6 = "pmgmbeeafpdjjhmeaalneginpmdhamhe" ascii wide
        $ext_7 = "eobcealmgdjeoheieiobkedbgddicaba" ascii wide
        $ext_8 = "lnedcnepmplnjmfdiclhbfhneconamoj" ascii wide
        $ext_9 = "gadjnphfolikkffmppnicebdfimlblkj" ascii wide
        $ext_10 = "njfkgeajknkffkngdmjmjninkbgjedlo" ascii wide
        $ext_11 = "eldjnmdpkecnjjkmmgndpcibgkfpodfh" ascii wide
        $ext_12 = "omieocempinhilcpbmnfdaamgomapded" ascii wide
        $ext_13 = "ilgbcnkedmncjlhpfconadpjnhlflejf" ascii wide
        $ext_14 = "okggiiagcegdfiajlkodohfkeemnjlnd" ascii wide
        $ext_15 = "jgajjllfidghjkjfipmjbaegafkdpfha" ascii wide
        $ext_16 = "gpibjjfllodpcfhcjpamonnblkbinbie" ascii wide
        $ext_17 = "hpdpddnfjaacnbcnoohlcipfafkbmdja" ascii wide
        $ext_18 = "lljnhidbljbfkejjcfogkhgmgdihjmlf" ascii wide
        $ext_19 = "gclgncjpanihjpbjbecgfmfnipggcckn" ascii wide
        $ext_20 = "cpehflfpgdgofpocagbdeecjlfhjfjdh" ascii wide
        $ext_21 = "mdenajpfccjjjnbochgkdahmnipfpelc" ascii wide
        $ext_22 = "eoclijfghiglinncpceohgaigfgnlbim" ascii wide
        $ext_23 = "cghdfcbncfjhleinblpalngjhojokjeo" ascii wide
        $ext_24 = "jeahgicmhigopdgilnmclihdjjlhnmop" ascii wide
        $ext_25 = "edbhdbhgdbanjhdnpjcianjgfmdkgbcf" ascii wide
        $ext_26 = "jjnfhbcilcppomkcmkbbmcadoihkkgah" ascii wide
        $ext_27 = "dmnajaiijohbndidolbdbpicdjanombo" ascii wide
        $ext_28 = "gpghebehjahceknfdcfifeifhdbongld" ascii wide
        $ext_29 = "gidejehfgombmkfflghejpncblgfkagj" ascii wide
        $ext_30 = "koolcjajfdkjjfklmidahmcjhcmmkhma" ascii wide
        $ext_31 = "gijlkeaijpeaoihdajcgmiajeoonnkoj" ascii wide
        $ext_32 = "kldgaejigkhpgmfglbamggiglngkifck" ascii wide
        $ext_33 = "ojlhcbolfcndnojcjhhjgmdblnojgefm" ascii wide
        $ext_34 = "eldjnmdpkecnjjkmmgndpcibgkfpodfh" ascii wide
        $ext_35 = "kiecdaoopedhfgapicmpebbhodepnbbp" ascii wide
        $ext_36 = "dmakkciciccnjgmfjflpbdfkdnmpfghp" ascii wide
        $ext_37 = "ebhcaliljppmelancooakfgcgcceiind" ascii wide
        $ext_38 = "eekblbhfmladafbmpgkdedmolbjkjbnc" ascii wide
        $ext_39 = "ejkdgndbgpfcaggpmnijcbddlnmdnpka" ascii wide
        $ext_40 = "fojomppheellamdaddnbgommepnlkooh" ascii wide
        $ext_41 = "gmbebpcapalekeaoekfhpbioilghcfmp" ascii wide
        $ext_42 = "ndcphhjcebhifabfmebineokbfdnbphm" ascii wide
        $ext_43 = "oghbffaoaooigagpockijkpfpgmnibkh" ascii wide
        $ext_44 = "oppeaknhldjjnfnflbcedipjbnbimhhf" ascii wide
        $ext_45 = "pcfapghfanllmbdfiipeiihpkojekckk" ascii wide
        $ext_46 = "lfmdddfdacgdimongmjclgijepoknmjm" ascii wide
        $ext_47 = "pmannhofeaiadkcdbcebhnkcnkjjnfpn" ascii wide
        $ext_48 = "lkbfbidpkbeicafnnhlaockggaknjolf" ascii wide
        $ext_49 = "adjpoipklnhlapjijccnemdhkcphcegd" ascii wide
        $ext_50 = "dkcjihabohaldgjkdmenepolojcjdaah" ascii wide
        $ext_51 = "iiegilogjnagependdonbfcmfmmaamon" ascii wide
        $ext_52 = "aiaaeimmjjeceodjpficfnjckenedbon" ascii wide
        $ext_53 = "alogdolelipkojjgggejccalcbdioolg" ascii wide
        $ext_54 = "fchgahponkgfomlgieipannlfanfbfak" ascii wide
        $ext_55 = "fojomppheellamdaddnbgommepnlkooh" ascii wide
        $ext_56 = "ldanhaibkdifncinbpjdjpambmofmpkf" ascii wide
        $ext_57 = "aehjmdkbfemaefoebbihbfcmhehgimcl" ascii wide
        $ext_58 = "bibjgkidgpfbblifamdlkdlhgihmfohh" ascii wide
        $ext_59 = "pkgciiiancapdlpcbppfkmeaieppikkk" ascii wide
        $ext_60 = "epdjhgbipjpbbhoccdeipghoihibnfja" ascii wide
        $ext_61 = "bbdnohkpnbkdkmnkddobeafboooinpla" ascii wide
        $ext_62 = "befflofjcniongenjmbkgkoljhgliihe" ascii wide
        $ext_63 = "cedgndijpacnfbdggppddacngjfdkaca" ascii wide
        $ext_64 = "nnpnnpemnckcfdebeekibpiijlicmpom" ascii wide
        $ext_65 = "dpggmcodlahmljkhlmpgpdcffdaoccni" ascii wide
        $ext_66 = "cplhlgabfijoiabgkigdafklbhhdkahj" ascii wide
        $ext_67 = "egmennebgadmncfjafcemlecimkepcle" ascii wide
        $ext_68 = "acmfnomgphggonodopogfbmkneepfgnh" ascii wide
        $ext_69 = "mnhffkhmpnefgklngfmlndmkimimbphc" ascii wide
        $ext_70 = "oaikpkmjciadfpddlpjjdapglcihgdle" ascii wide
        $ext_71 = "fbmlcbhdmilaggedifpihjgkkmdgeljh" ascii wide
        $ext_72 = "kkodiihpgodmdankclfibbiphjkfdenh" ascii wide
        $ext_73 = "oeiomhmbaapihbilkfkhmlajkeegnjhe" ascii wide
        $ext_74 = "jiofmdifioeejeilfkpegipdjiopiekl" ascii wide
        $ext_75 = "hihblcmlaaademjlakdpicchbjnnnkbo" ascii wide
        $ext_76 = "ndlbedplllcgconngcnfmkadhokfaaln" ascii wide
        $ext_77 = "igbodamhgjohafcenbcljfegbipdfjpk" ascii wide
        $ext_78 = "bgejafhieobnfpjlpcjjggoboebonfcg" ascii wide
        $ext_79 = "llimhhconnjiflfimocjggfjdlmlhblm" ascii wide
        $ext_80 = "hodiladlefdpcbemnbbcpclbmknkiaem" ascii wide
        $ext_81 = "epikoohpebngmakjinphfiagogjcnddm" ascii wide
        $ext_82 = "pajkjnmeojmbapicmbpliphjmcekeaac" ascii wide
        $ext_83 = "ogbhbgkiojdollpjbhbamafmedkeockb" ascii wide
        $ext_84 = "eanofdhdfbcalhflpbdipkjjkoimeeod" ascii wide
        $ext_85 = "ekpkdmohpdnebfedjjfklhpefgpgaaji" ascii wide
        $ext_86 = "miglaibdlgminlepgeifekifakochlka" ascii wide
        $ext_87 = "mbindhfolmpijhodmgkloeeppmkhpmhc" ascii wide
        $ext_88 = "eaijffijbobmnonfhilihbejadplhddo" ascii wide
        $ext_89 = "lbneaaedflankmgmfbmaplggbmjjmbae" ascii wide
        $ext_90 = "hmiaoahjllhfgebflooeeefeiafpkfde" ascii wide
        $ext_91 = "pdkmmfdfggfpibdjbbghggcllhhainjo" ascii wide
        $ext_92 = "emedckhdnioeieppmeojgegjfkhdlaeo" ascii wide
        $ext_93 = "didhgeamncokiaegffipckhhcpnmlcbl" ascii wide

    condition:
        any of ($ext_*)
}

rule ExtSentry_cryptocurrency_BrowserExtensions
{
    meta:
        description = "Detects browser extension IDs categorized as cryptocurrency by ExtSentry"
        author = "ExtSentry / mthcht"
        date = "2026-03-27"
        reference = "https://github.com/mthcht/awesome-lists"
        category = "cryptocurrency"
        tlp = "WHITE"

    strings:
        $ext_0 = "fhbohimaelbohpjbbldcngcnapnedx765dodjp" ascii wide
        $ext_1 = "fnjhmkhhmkbedx765jkkabndcnnogagogbneec" ascii wide
        $ext_2 = "gcmjkmgdlgnkkcocmoeiminaijmmjnii" ascii wide
        $ext_3 = "heamnjbnflcikcggoiplibfommfbkjpj" ascii wide
        $ext_4 = "egjidjbpglichdcondbcbdnbeeppgdph" ascii wide
        $ext_5 = "ibnejdfjmmkpcnlpebklmnkoeoihofec" ascii wide
        $ext_6 = "nphplpgoakhhjchkkhmiggakijnkhfnd" ascii wide
        $ext_7 = "mfgccjchihfkkindfppnaooecgfneiii" ascii wide
        $ext_8 = "lgmpcpglpngdoalbgeoldeajfclnhafa" ascii wide
        $ext_9 = "fnjhmkhhmkbjkkabndcnnogagogbneec" ascii wide
        $ext_10 = "jnmbobjmhlngoefaiojfljckilhhlhcj" ascii wide
        $ext_11 = "mcohilncbfahbmgdjkbpemcciiolgcge" ascii wide
        $ext_12 = "hpglfhgfnhbgpjdenjgmdgoeiappafln" ascii wide
        $ext_13 = "aholpfdialjgjfhomihkjbmgjidlcdno" ascii wide
        $ext_14 = "mcbigmjiafegjnnogedioegffbooigli" ascii wide
        $ext_15 = "kkpllkodjeloidieedojogacfhpaihoh" ascii wide
        $ext_16 = "hifafgmccdpekplomjjkcfgodnhcellj" ascii wide
        $ext_17 = "odbfpeeihdkbihmopkbjmoonfanlbfcl" ascii wide
        $ext_18 = "bopcbmipnjdcdfflfgjdgdjejmgpoaab" ascii wide
        $ext_19 = "jiidiaalihmmhddjgbnbgdfflelocpak" ascii wide
        $ext_20 = "dlcobpjiigpikoobohmabehhmhfoodbb" ascii wide
        $ext_21 = "cnmamaachppnkjgnildpdmkaakejnhae" ascii wide
        $ext_22 = "fhbohimaelbohpjbbldcngcnapndodjp" ascii wide
        $ext_23 = "ijmpgkjfkbfhoebgogflfebnmejmfbml" ascii wide
        $ext_24 = "oijajbhmelbcoclnkdmembiacmeghbae" ascii wide
        $ext_25 = "fihkakfobkmkjojpchpfgcmhfjnmnfpi" ascii wide
        $ext_26 = "nlgbhdfgdhgbiamfdfmbikcdghidoadd" ascii wide
        $ext_27 = "apnehcjmnengpnmccpaibjmhhoadaico" ascii wide
        $ext_28 = "nhnkbkgjikgcigadomkphalanndcapjk" ascii wide
        $ext_29 = "aeachknmefphepccionboohckonoeemg" ascii wide
        $ext_30 = "dhgnlgphgchebgoemcjekedjjbifijid" ascii wide
        $ext_31 = "dkdedlpgdmmkkfjabffeganieamfklkm" ascii wide
        $ext_32 = "blnieiiffboillknjnepogjhkgnoapac" ascii wide
        $ext_33 = "hnhobjmcibchnmglfbldbfabcgaknlkj" ascii wide
        $ext_34 = "copjnifcecdedocejpaapepagaodgpbh" ascii wide
        $ext_35 = "jbdaocneiiinmjbjlgalhcelgbejmnid" ascii wide
        $ext_36 = "nkddgncdjgjfcddamfgcmfnlhccnimig" ascii wide
        $ext_37 = "nanjmdknhkinifnkgdcggcfnhdaammmj" ascii wide
        $ext_38 = "bcopgchhojmggmffilplmbdicgaihlkp" ascii wide
        $ext_39 = "flpiciilemghbmfalicajoolhkkenfel" ascii wide
        $ext_40 = "kncchdigobghenbbaddojjnnaogfppfj" ascii wide
        $ext_41 = "dmkamcknogkgcdfhhbddcghachkejeap" ascii wide
        $ext_42 = "hcflpincpppdclinealmandijcmnkbgn" ascii wide
        $ext_43 = "cihmoadaighcejopammfbmddcmdekcje" ascii wide
        $ext_44 = "kpfopkelmapcoipemfendmdcghnegimn" ascii wide
        $ext_45 = "afbcbjpbpfadlkmhmclhkeeodmamcflc" ascii wide
        $ext_46 = "nkbihfbeogaeaoehlefnkodbefgpgknn" ascii wide
        $ext_47 = "ejbalbakoplchlghecdaedx765lmeeeajnimhm" ascii wide
        $ext_48 = "bkklifkecemccedpkhcebagjpehhabfb" ascii wide
        $ext_49 = "nlbmnnijcnlegkjjpcfjclmcfggfefdm" ascii wide
        $ext_50 = "nknhiehlklippafakaeklbeglecifhad" ascii wide
        $ext_51 = "lpfcbjknijpeeillifnkikgncikgfhdo" ascii wide
        $ext_52 = "onofpnbbkehpmmoabgpcpmigafmmnjhl" ascii wide
        $ext_53 = "jbdaocneiiinmjbjlgalhcelgbejmnid" ascii wide
        $ext_54 = "ibnejdfjmmkpcnlpebklmnkoeoihofec" ascii wide
        $ext_55 = "nkbihfbeogaeaoehlefnkodbefgpgknn" ascii wide
        $ext_56 = "fhbohimaelbohpjbbldcngcnapndodjp" ascii wide
        $ext_57 = "ffnbelfdoeiohenkjibnmadjiehjhajb" ascii wide
        $ext_58 = "cjelfplplebdjjenllpjcblmjkfcffne" ascii wide
        $ext_59 = "gaedmjdfmmahhbjefcbgaolhhanlaolb" ascii wide
        $ext_60 = "bhghoamapcdpbohphigoooaddinpkbai" ascii wide
        $ext_61 = "fihkakfobkmkjojpchpfgcmhfjnmnfpi" ascii wide
        $ext_62 = "ijmpgkjfkbfhoebgogflfebnmejmfbml" ascii wide
        $ext_63 = "jiidiaalihmmhddjgbnbgdfflelocpak" ascii wide
        $ext_64 = "okejhknhopdbemmfefjglkdfdhpfmflg" ascii wide
        $ext_65 = "hkkpjehhcnhgefhbdcgfkeegglpjchdc" ascii wide
        $ext_66 = "aeachknmefphepccionboohckonoeemg" ascii wide
        $ext_67 = "hnfanknocfeofbddgcijnmhnfnkdnaad" ascii wide
        $ext_68 = "dkdedlpgdmmkkfjabffeganieamfklkm" ascii wide
        $ext_69 = "blnieiiffboillknjnepogjhkgnoapac" ascii wide
        $ext_70 = "oeljdldpnmdbchonielidgobddffflal" ascii wide
        $ext_71 = "aholpfdialjgjfhomihkjbmgjidlcdno" ascii wide
        $ext_72 = "ghocjofkdpicneaokfekohclmkfmepbp" ascii wide
        $ext_73 = "cjmkndjhnagcfbpiemnkdpomccnjblmj" ascii wide
        $ext_74 = "ilgcnhelpchnceeipipijaljkblbcobl" ascii wide
        $ext_75 = "hpglfhgfnhbgpjdenjgmdgoeiappafln" ascii wide
        $ext_76 = "acdamagkdfmpkclpoglgnbddngblgibo" ascii wide
        $ext_77 = "flpiciilemghbmfalicajoolhkkenfel" ascii wide
        $ext_78 = "kncchdigobghenbbaddojjnnaogfppfj" ascii wide
        $ext_79 = "knogkgcdfhhbddcghachkejeap" ascii wide
        $ext_80 = "kpfopkelmapcoipemfendmdcghnegimn" ascii wide
        $ext_81 = "afbcbjpbpfadlkmhmclhkeeodmamcflc" ascii wide
        $ext_82 = "ejbalbakoplchlghecdalmeeeajnimhm" ascii wide
        $ext_83 = "djclckkglechooblngghdinmeemkbgci" ascii wide
        $ext_84 = "fcckkdbjnoikooededlapcalpionmalo" ascii wide
        $ext_85 = "jbdaocneiiinmjbjlgalhcelgbejmnid" ascii wide
        $ext_86 = "bfnaelmomeimhlpmgjnjophhpkkoljpa" ascii wide
        $ext_87 = "hgmoaheomcjnaheggkfafnjilfcefbmo" ascii wide
        $ext_88 = "fnjhmkhhmkbjkkabndcnnogagogbneec" ascii wide
        $ext_89 = "hfljlochmlccoobkbcgpmkpjagogcgpk" ascii wide
        $ext_90 = "cmndjbecilbocjfkibfbifhngkdmjgog" ascii wide
        $ext_91 = "mnfifefkajgofkcjkemidiaecocnkjeh" ascii wide
        $ext_92 = "aiifbnbfobpmeekipheeijimdpnlpgpp" ascii wide
        $ext_93 = "imloifkgjagghnncjkhggdhalmcnfklk" ascii wide
        $ext_94 = "egjidjbpglichdcondbcbdnbeeppgdph" ascii wide
        $ext_95 = "heaomjafhiehddpnmncmhhpjaloainkn" ascii wide
        $ext_96 = "mijjdbgpgbflkaooedaemnlciddmamai" ascii wide
        $ext_97 = "amkmjjmmflddogmhpjloimipbofnfjih" ascii wide
        $ext_98 = "bocpokimicclpaiekenaeelehdjllofo" ascii wide
        $ext_99 = "hmeobnfnfcmdkdcmlblgagmfpfboieaf" ascii wide
        $ext_100 = "akoiaibnepcedcplijmiamnaigbepmcb" ascii wide
        $ext_101 = "klnaejjgbibmhlephnhpmaofohgkpgkd" ascii wide
        $ext_102 = "ppdadbejkmjnefldpcdjhnkpbjkikoip" ascii wide
        $ext_103 = "infeboajgfhgbjpjbeppbkgnabfdkdaf" ascii wide
        $ext_104 = "bfnaelmomeimhlpmgjnjophhpkkoljpa" ascii wide
        $ext_105 = "jojhfeoedkpkglbfimdfabpdfjaoolaf" ascii wide
        $ext_106 = "acmacodkjbdgmoleebolmdjonilkdbch" ascii wide
        $ext_107 = "cphhlgmgameodnhkjdmkpanlelnlohao" ascii wide
        $ext_108 = "fhmfendgdocmcbmfikdcogofphimnkno" ascii wide
        $ext_109 = "aiifbnbfobpmeekipheeijimdpnlpgpp" ascii wide
        $ext_110 = "ookjlbkiijinhpmnjffcofjonbfbgaoc" ascii wide
        $ext_111 = "mnfifefkajgofkcjkemidiaecocnkjeh" ascii wide
        $ext_112 = "pnndplcbkakcplkjnolgbkdgjikjednm" ascii wide
        $ext_113 = "amkmjjmmflddogmhpjloimipbofnfjih" ascii wide
        $ext_114 = "hmeobnfnfcmdkdcmlblgagmfpfboieaf" ascii wide
        $ext_115 = "ffnbelfdoeiohenkjibnmadjiehjhajb" ascii wide
        $ext_116 = "ejbalbakoplchlghecdalmeeeajnimhm" ascii wide

    condition:
        any of ($ext_*)
}

rule ExtSentry_Credential_Access_BrowserExtensions
{
    meta:
        description = "Detects browser extension IDs categorized as Credential_Access by ExtSentry"
        author = "ExtSentry / mthcht"
        date = "2026-03-27"
        reference = "https://github.com/mthcht/awesome-lists"
        category = "Credential_Access"
        tlp = "WHITE"

    strings:
        $ext_0 = "akoofbljmjeodfmdpjndmmnifglppjdi" ascii wide
        $ext_1 = "ijacbjjjpmhencpkoghphdgbooifplmn" ascii wide

    condition:
        any of ($ext_*)
}

rule ExtSentry_Defense_Evasion_BrowserExtensions
{
    meta:
        description = "Detects browser extension IDs categorized as Defense_Evasion by ExtSentry"
        author = "ExtSentry / mthcht"
        date = "2026-03-27"
        reference = "https://github.com/mthcht/awesome-lists"
        category = "Defense_Evasion"
        tlp = "WHITE"

    strings:
        $ext_0 = "hdemabfejemmmicoabglpocdmmkjphpo" ascii wide

    condition:
        any of ($ext_*)
}

rule ExtSentry_scam_BrowserExtensions
{
    meta:
        description = "Detects browser extension IDs categorized as scam by ExtSentry"
        author = "ExtSentry / mthcht"
        date = "2026-03-27"
        reference = "https://github.com/mthcht/awesome-lists"
        category = "scam"
        tlp = "WHITE"

    strings:
        $ext_0 = "aopkheicgfmacnpdebpdffbhfilcoecb" ascii wide
        $ext_1 = "bmnlcjabgnpnenekpadlanbbkooimhnj" ascii wide
        $ext_2 = "oleahcaoibfbcoejnabdeleldpicbjgi" ascii wide
        $ext_3 = "amnbcmdbanbkjhnfoeceemmmdiepnbpp" ascii wide
        $ext_4 = "jid1-93CWPmRbVPjRQA@jetpack" ascii wide

    condition:
        any of ($ext_*)
}

rule ExtSentry_RMM_BrowserExtensions
{
    meta:
        description = "Detects browser extension IDs categorized as RMM by ExtSentry"
        author = "ExtSentry / mthcht"
        date = "2026-03-27"
        reference = "https://github.com/mthcht/awesome-lists"
        category = "RMM"
        tlp = "WHITE"

    strings:
        $ext_0 = "bfleegjcoffelppfmadimianphbcdjkb" ascii wide

    condition:
        any of ($ext_*)
}

rule ExtSentry_PUP_BrowserExtensions
{
    meta:
        description = "Detects browser extension IDs categorized as PUP by ExtSentry"
        author = "ExtSentry / mthcht"
        date = "2026-03-27"
        reference = "https://github.com/mthcht/awesome-lists"
        category = "PUP"
        tlp = "WHITE"

    strings:
        $ext_0 = "dhkplhfnhceodhffomolpfigojocbpcb" ascii wide
        $ext_1 = "pfmopbbadnfoelckkcmjjeaaegjpjjbk" ascii wide
        $ext_2 = "aaaailpifkkekipiachodfkfmgmiapmp" ascii wide

    condition:
        any of ($ext_*)
}

rule ExtSentry_password_manager_BrowserExtensions
{
    meta:
        description = "Detects browser extension IDs categorized as password_manager by ExtSentry"
        author = "ExtSentry / mthcht"
        date = "2026-03-27"
        reference = "https://github.com/mthcht/awesome-lists"
        category = "password_manager"
        tlp = "WHITE"

    strings:
        $ext_0 = "imloifkgjagghnncjkhggdhalmcnfklk" ascii wide
        $ext_1 = "fdjamakpfbbddfjaooikfcpapjohcfmg" ascii wide
        $ext_2 = "hdokiejnpimakedhajhdlcegeplioahd" ascii wide
        $ext_3 = "caljgklbbfbcjjanaijlacgncafpegll" ascii wide
        $ext_4 = "admmjipmmciaobhojoghlmleefbicajg" ascii wide
        $ext_5 = "bfogiafebfohielmmehodmfbbebbbpei" ascii wide
        $ext_6 = "nngceckbapebfimnlniiiahkandclblb" ascii wide
        $ext_7 = "aeblfdkhhhdcdjpifhhbdiojplfjncoa" ascii wide
        $ext_8 = "ghmbeldphafepmbegfdlkpapadhbakde" ascii wide

    condition:
        any of ($ext_*)
}

rule ExtSentry_PROXY_VPN_BrowserExtensions
{
    meta:
        description = "Detects browser extension IDs categorized as PROXY_VPN by ExtSentry"
        author = "ExtSentry / mthcht"
        date = "2026-03-27"
        reference = "https://github.com/mthcht/awesome-lists"
        category = "PROXY_VPN"
        tlp = "WHITE"

    strings:
        $ext_0 = "fjoaledfpmneenckfbpdfhkmimnjocfa" ascii wide
        $ext_1 = "fphgeikpdcdcheaochkhldmnfblfogla" ascii wide
        $ext_2 = "ffbkglfijbcbgblgflchnbphjdllaogb" ascii wide
        $ext_3 = "akcocjjpkmlniicdeemdceeajlmoabhg" ascii wide
        $ext_4 = "fgddmllnllkalaagkghckoinaemmogpe" ascii wide

    condition:
        any of ($ext_*)
}

import "hash"

rule ExtSentry_CRX_SHA256_Hashes
{
    meta:
        description = "Detects known malicious CRX files by SHA-256 hash"
        author = "ExtSentry"
        date = "2026-03-27"
        reference = "https://github.com/mthcht/awesome-lists"
        tlp = "WHITE"

    condition:
                hash.sha256(0, filesize) == "0cbf101e96f6d5c4146812f07105f8b89bd76dd994f540470cd1c4bc37df37d5" or
                hash.sha256(0, filesize) == "21dd863ff9bbd15da01c1218bf92bd65eeae04a41876e10c41733b58035414c4" or
                hash.sha256(0, filesize) == "9d0f550ac883455ed64da402cdb0c822c90de405c540678e0697b77fe20de3cf" or
                hash.sha256(0, filesize) == "a25a3e108f62a10caa2b736123ca7350e9dbc1b888c44e909cbd6866205ca671" or
                hash.sha256(0, filesize) == "4a2f0f1893527e4c419f36c2e4f95a61617074200bb67218fb96ae74125e433b" or
                hash.sha256(0, filesize) == "5629be21869a83e9b9da86ab16a2d9cebd0aed2c04a9efe2ac044dfe0d5db6b9" or
        hash.sha256(0, filesize) == "cdae573ab468b24c28a42d6078daf2da1a4b4c5657a4146ad966e2fe8340cb49"
}
